#include "models/byte_table_model.h"

#include "core/byte_format_utils.h"
#include "data/byte_data_source.h"
#include "features/columns/column_color_palette.h"
#include "features/framing/frame_layout.h"

#include <QBrush>
#include <QColor>
#include <QFutureWatcher>
#include <QStringView>
#include <QtConcurrent>
#include <QtGlobal>

#include <algorithm>
#include <array>
#include <limits>

namespace bitabyte::models {
namespace {

struct DefinitionSpanInfo {
    int definitionIndex = -1;
    int startBit = 0;
    int endBit = -1;
    int startByte = 0;
    int endByte = -1;
    features::columns::VisibleByteColumn visibleColumn;
};

QString formatBitStartLabel(qsizetype bitOffset) {
    if (bitOffset < 0) {
        return {};
    }

    const qsizetype byteOffset = bitOffset / 8;
    const int bitOffsetInByte = static_cast<int>(bitOffset % 8);
    if (bitOffsetInByte == 0) {
        return core::formatByteOffset(byteOffset);
    }

    return QStringLiteral("%1+%2b").arg(core::formatByteOffset(byteOffset)).arg(bitOffsetInByte);
}

QString normalizedDisplayFormat(const QString& displayFormat) {
    const QString loweredFormat = displayFormat.trimmed().toLower();
    if (loweredFormat == QStringLiteral("dec")) {
        return QStringLiteral("decimal");
    }
    return loweredFormat.isEmpty() ? QStringLiteral("hex") : loweredFormat;
}

bool isAutoGeneratedLabel(const QString& labelText) {
    const QString trimmedLabel = labelText.trimmed();
    return trimmedLabel.isEmpty()
        || trimmedLabel.startsWith(QStringLiteral("BIN "))
        || trimmedLabel.startsWith(QStringLiteral("NIBBLE "))
        || trimmedLabel.startsWith(QStringLiteral("Byte "))
        || trimmedLabel.startsWith(QStringLiteral("Bytes "))
        || trimmedLabel.startsWith(QStringLiteral("Combo "));
}

QColor blendHighlightColor(const QColor& baseColor, const QColor& highlightColor, double highlightWeight) {
    if (!baseColor.isValid()) {
        return highlightColor;
    }

    const double clampedWeight = qBound(0.0, highlightWeight, 1.0);
    const double baseWeight = 1.0 - clampedWeight;
    return QColor(
        qRound((baseColor.red() * baseWeight) + (highlightColor.red() * clampedWeight)),
        qRound((baseColor.green() * baseWeight) + (highlightColor.green() * clampedWeight)),
        qRound((baseColor.blue() * baseWeight) + (highlightColor.blue() * clampedWeight))
    );
}

bool hasSnapshotDisplayValue(
    qsizetype rowLengthBits,
    const features::columns::VisibleByteColumn& visibleColumn
) {
    return visibleColumn.absoluteEndBit < rowLengthBits;
}

QByteArray rowBitsForSnapshotVisibleColumn(
    const data::ByteDataSource& dataSource,
    qsizetype rowStartBit,
    qsizetype rowLengthBits,
    const features::columns::VisibleByteColumn& visibleColumn
) {
    if (rowStartBit < 0 || !hasSnapshotDisplayValue(rowLengthBits, visibleColumn)) {
        return {};
    }

    const qsizetype absoluteStartBit = rowStartBit + visibleColumn.absoluteStartBit;
    return dataSource.bitRange(absoluteStartBit, visibleColumn.bitWidth());
}

const QColor kConstantHighlightColor(255, 247, 196);
const QColor kCounterHighlightColor(212, 232, 255);
const QColor kPatternHighlightColor(220, 245, 255);

bool rangesOverlap(
    qsizetype startBit,
    qsizetype endBit,
    const QVector<QPair<qsizetype, qsizetype>>& ranges
) {
    if (ranges.isEmpty() || endBit < startBit) {
        return false;
    }

    const auto candidate = std::lower_bound(
        ranges.begin(),
        ranges.end(),
        startBit,
        [](const QPair<qsizetype, qsizetype>& range, qsizetype value) {
            return range.second < value;
        }
    );
    return candidate != ranges.end() && candidate->first <= endBit;
}

bool byteColumnDefinitionsEqual(
    const QVector<features::columns::ByteColumnDefinition>& leftDefinitions,
    const QVector<features::columns::ByteColumnDefinition>& rightDefinitions
) {
    if (leftDefinitions.size() != rightDefinitions.size()) {
        return false;
    }

    for (int definitionIndex = 0; definitionIndex < leftDefinitions.size(); ++definitionIndex) {
        const features::columns::ByteColumnDefinition& leftDefinition = leftDefinitions.at(definitionIndex);
        const features::columns::ByteColumnDefinition& rightDefinition = rightDefinitions.at(definitionIndex);
        if (leftDefinition.label != rightDefinition.label
            || leftDefinition.startByte != rightDefinition.startByte
            || leftDefinition.endByte != rightDefinition.endByte
            || leftDefinition.unit != rightDefinition.unit
            || leftDefinition.startBit != rightDefinition.startBit
            || leftDefinition.totalBits != rightDefinition.totalBits
            || leftDefinition.displayFormat != rightDefinition.displayFormat
            || leftDefinition.colorName != rightDefinition.colorName) {
            return false;
        }
    }

    return true;
}

QVector<int> constantVisibleColumnIndicesForSnapshot(
    const data::ByteDataSource& dataSource,
    const features::framing::FrameLayout& frameLayout,
    const QVector<features::columns::VisibleByteColumn>& visibleColumns
) {
    QVector<int> constantVisibleColumnIndices;
    if (!dataSource.hasData() || visibleColumns.isEmpty()) {
        return constantVisibleColumnIndices;
    }

    const int totalRowCount = static_cast<int>(frameLayout.rowCount(dataSource));
    if (totalRowCount <= 0) {
        return constantVisibleColumnIndices;
    }

    struct RowGeometry {
        qsizetype startBit;
        qsizetype lengthBits;
    };
    QVector<RowGeometry> rowGeometries;
    rowGeometries.reserve(totalRowCount);
    for (int row = 0; row < totalRowCount; ++row) {
        rowGeometries.append({
            frameLayout.rowStartBit(dataSource, row),
            frameLayout.rowLengthBits(dataSource, row),
        });
    }

    constantVisibleColumnIndices.reserve(visibleColumns.size());
    for (int visibleColumnIndex = 0; visibleColumnIndex < visibleColumns.size(); ++visibleColumnIndex) {
        const features::columns::VisibleByteColumn& visibleColumn = visibleColumns.at(visibleColumnIndex);
        if (visibleColumn.isUndefined) {
            continue;
        }

        QByteArray referenceBits;
        bool hasReferenceValue = false;
        bool allRowsMatch = true;
        int analyzedRowCount = 0;

        for (int row = 0; row < totalRowCount; ++row) {
            const QByteArray rowBits = rowBitsForSnapshotVisibleColumn(
                dataSource,
                rowGeometries.at(row).startBit,
                rowGeometries.at(row).lengthBits,
                visibleColumn
            );
            if (rowBits.isEmpty()) {
                continue;
            }

            ++analyzedRowCount;
            if (!hasReferenceValue) {
                referenceBits = rowBits;
                hasReferenceValue = true;
                continue;
            }

            if (rowBits != referenceBits) {
                allRowsMatch = false;
                break;
            }
        }

        if (allRowsMatch && analyzedRowCount == totalRowCount && analyzedRowCount > 0) {
            constantVisibleColumnIndices.append(visibleColumnIndex);
        }
    }

    return constantVisibleColumnIndices;
}

}  // namespace

ByteTableModel::ByteTableModel(
    data::ByteDataSource* dataSource,
    features::framing::FrameLayout* frameLayout,
    const QVector<features::columns::ByteColumnDefinition>* columnDefinitions,
    QObject* parent
)
    : QAbstractTableModel(parent),
      dataSource_(dataSource),
      frameLayout_(frameLayout),
      columnDefinitions_(columnDefinitions),
      constantHighlightWatcher_(new QFutureWatcher<QVector<int>>(this)) {
    connect(constantHighlightWatcher_, &QFutureWatcher<QVector<int>>::finished, this, [this]() {
        if (constantHighlightWatcher_ == nullptr) {
            return;
        }

        if (activeConstantHighlightRequestId_ == constantHighlightRequestId_ && constantColumnHighlightEnabled_) {
            constantVisibleColumnIndices_.clear();
            const QVector<int> constantVisibleColumns = constantHighlightWatcher_->result();
            for (int visibleColumnIndex : constantVisibleColumns) {
                constantVisibleColumnIndices_.insert(visibleColumnIndex);
            }
            if (rowCount() > 0 && columnCount() > 0) {
                emit dataChanged(
                    index(0, 0),
                    index(rowCount() - 1, columnCount() - 1),
                    {Qt::BackgroundRole}
                );
            }
        }

        if (constantColumnHighlightEnabled_ && activeConstantHighlightRequestId_ != constantHighlightRequestId_) {
            startConstantVisibleColumnCacheRebuild();
        }
    });
    monospaceFont_.setFamilies({
        QStringLiteral("Consolas"),
        QStringLiteral("Courier New"),
        QStringLiteral("Monospace"),
    });
    monospaceFont_.setStyleHint(QFont::StyleHint::Monospace);
    monospaceFont_.setHintingPreference(QFont::HintingPreference::PreferFullHinting);
    rebuildVisibleColumns();
}

int ByteTableModel::rowCount(const QModelIndex& parent) const {
    if (parent.isValid() || dataSource_ == nullptr || frameLayout_ == nullptr) {
        return 0;
    }

    return static_cast<int>(frameLayout_->rowCount(*dataSource_));
}

int ByteTableModel::columnCount(const QModelIndex& parent) const {
    if (parent.isValid() || dataSource_ == nullptr || frameLayout_ == nullptr) {
        return 0;
    }

    return visibleColumnCount() + (hasFrameLengthColumn() ? 1 : 0);
}

QVariant ByteTableModel::data(const QModelIndex& modelIndex, int role) const {
    if (!modelIndex.isValid() || dataSource_ == nullptr || frameLayout_ == nullptr) {
        return {};
    }

    if (isFrameLengthColumn(modelIndex.column())) {
        if (role == Qt::DisplayRole) {
            return frameLayout_->rowLengthBytes(*dataSource_, modelIndex.row());
        }

        if (role == Qt::TextAlignmentRole) {
            return Qt::AlignCenter;
        }

        if (role == Qt::FontRole) {
            return monospaceFont_;
        }

        if (role == Qt::BackgroundRole) {
            return QBrush(QColor(232, 238, 246));
        }

        if (role == Qt::ToolTipRole) {
            const qsizetype frameLengthBits = frameLayout_->rowLengthBits(*dataSource_, modelIndex.row());
            const int frameLengthBytes = frameLayout_->rowLengthBytes(*dataSource_, modelIndex.row());
            return QStringLiteral("Frame length %1 bytes | %2 bits")
                .arg(frameLengthBytes)
                .arg(frameLengthBits);
        }

        return {};
    }

    const int visibleColumnIndex = visibleColumnIndexForModelIndex(modelIndex);
    if (visibleColumnIndex < 0 || visibleColumnIndex >= visibleColumns_.size()) {
        return {};
    }

    const features::columns::VisibleByteColumn visibleColumn = visibleColumns_.at(visibleColumnIndex);
    const qsizetype startBit = displayStartBitForIndex(modelIndex);

    if (role == Qt::DisplayRole) {
        return formatVisibleColumnDisplayText(modelIndex.row(), visibleColumn);
    }

    if (role == Qt::TextAlignmentRole) {
        return Qt::AlignCenter;
    }

    if (role == Qt::FontRole) {
        return monospaceFont_;
    }

    if (role == Qt::BackgroundRole) {
        if (!hasDisplayValue(modelIndex.row(), visibleColumn)) {
            return QBrush(QColor(242, 242, 242));
        }
        QColor backgroundColor = backgroundForVisibleColumn(visibleColumnIndex, visibleColumn);
        const qsizetype cellStartBit = rowStartBit(modelIndex.row()) + visibleColumn.absoluteStartBit;
        const qsizetype cellEndBit = rowStartBit(modelIndex.row()) + visibleColumn.absoluteEndBit;
        if (rangesOverlap(cellStartBit, cellEndBit, patternHighlightRanges_)) {
            backgroundColor = blendHighlightColor(
                backgroundColor,
                kPatternHighlightColor,
                backgroundColor.isValid() ? 0.65 : 1.0
            );
        }
        if (backgroundColor.isValid()) {
            return QBrush(backgroundColor);
        }
        return {};
    }

    if (role == Qt::ToolTipRole) {
        return formatVisibleColumnToolTip(modelIndex.row(), startBit, visibleColumn);
    }

    return {};
}

QVariant ByteTableModel::headerData(int section, Qt::Orientation orientation, int role) const {
    if (dataSource_ == nullptr || frameLayout_ == nullptr) {
        return {};
    }

    if (role == Qt::DisplayRole) {
        if (orientation == Qt::Horizontal) {
            if (isFrameLengthColumn(section)) {
                return QStringLiteral("Len");
            }

            const int visibleColumnIndex = visibleColumnIndexForModelColumn(section);
            if (visibleColumnIndex < 0 || visibleColumnIndex >= visibleColumns_.size()) {
                return {};
            }
            return bottomHeaderLabelForVisibleColumn(visibleColumnIndex);
        }

        return formatRowHeaderText(section);
    }

    if (role == Qt::TextAlignmentRole) {
        return Qt::AlignCenter;
    }

    if (role == Qt::FontRole) {
        return monospaceFont_;
    }

    return {};
}

Qt::ItemFlags ByteTableModel::flags(const QModelIndex& modelIndex) const {
    if (!modelIndex.isValid()) {
        return Qt::NoItemFlags;
    }

    return Qt::ItemIsEnabled | Qt::ItemIsSelectable;
}

qsizetype ByteTableModel::displayStartBitForIndex(const QModelIndex& modelIndex) const {
    if (!modelIndex.isValid() || isFrameLengthColumn(modelIndex.column())) {
        return -1;
    }

    return cellStartBit(modelIndex.row(), modelIndex.column());
}

bool ByteTableModel::hasFrameLengthColumn() const {
    return frameLayout_ != nullptr && frameLayout_->isFramed();
}

bool ByteTableModel::isFrameLengthColumn(int col) const {
    return hasFrameLengthColumn() && col == 0;
}

int ByteTableModel::visibleColumnIndexForModelIndex(const QModelIndex& modelIndex) const {
    if (!modelIndex.isValid()) {
        return -1;
    }

    return visibleColumnIndexForModelColumn(modelIndex.column());
}

int ByteTableModel::visibleColumnCount() const {
    return visibleColumns_.size();
}

features::columns::VisibleByteColumn ByteTableModel::visibleByteColumn(int visibleColumn) const {
    if (visibleColumn < 0 || visibleColumn >= visibleColumns_.size()) {
        return {};
    }

    return visibleColumns_.at(visibleColumn);
}

bool ByteTableModel::hasSplit(int byteIndex) const {
    return splitColumns_.contains(byteIndex);
}

bool ByteTableModel::canSplitByte(int byteIndex) const {
    if (isBitDisplayMode()) {
        return false;
    }

    if (byteIndex < 0 || byteIndex >= displayWidthBytes()) {
        return false;
    }

    if (splitColumns_.contains(byteIndex)) {
        return false;
    }

    if (byteIndex >= byteColumnStarts_.size() || byteIndex >= byteColumnCounts_.size()) {
        return false;
    }

    const int startColumn = byteColumnStarts_.at(byteIndex);
    const int columnCountForByte = byteColumnCounts_.at(byteIndex);
    if (startColumn < 0 || columnCountForByte != 1) {
        return false;
    }

    const features::columns::VisibleByteColumn visibleColumn = visibleColumns_.at(startColumn);
    return !visibleColumn.isUndefined
        && visibleColumn.definitionIndex < 0
        && visibleColumn.splitLabel.isEmpty()
        && visibleColumn.bitStart == 0
        && visibleColumn.bitEnd == 7;
}

bool ByteTableModel::applySplit(const QSet<int>& byteIndices, const QString& splitType) {
    if (isBitDisplayMode()) {
        return false;
    }

    const QString normalizedSplitType = splitType.trimmed().toLower();
    if (byteIndices.isEmpty()
        || (normalizedSplitType != QStringLiteral("binary") && normalizedSplitType != QStringLiteral("nibble"))) {
        return false;
    }

    bool changed = false;
    const QString labelPrefix = normalizedSplitType == QStringLiteral("binary")
        ? QStringLiteral("BIN")
        : QStringLiteral("NIBBLE");
    QSet<QString> usedColors;

    beginResetModel();
    for (int byteIndex : byteIndices) {
        if (!canSplitByte(byteIndex)) {
            continue;
        }

        SplitColumnState splitState;
        splitState.type = normalizedSplitType;
        splitState.label = QStringLiteral("%1 %2").arg(labelPrefix).arg(nextSplitLabelIndex(labelPrefix));
        splitState.colorName = nextAutoSplitColorName(
            normalizedSplitType == QStringLiteral("binary") ? QStringLiteral("Sky") : QStringLiteral("Coral"),
            usedColors
        );
        usedColors.insert(splitState.colorName);
        splitColumns_.insert(byteIndex, splitState);
        changed = true;
    }

    if (changed) {
        rebuildVisibleColumns();
    }
    endResetModel();
    return changed;
}

bool ByteTableModel::clearSplits(const QSet<int>& byteIndices) {
    if (isBitDisplayMode()) {
        return false;
    }

    if (byteIndices.isEmpty()) {
        return false;
    }

    bool changed = false;
    beginResetModel();
    for (int byteIndex : byteIndices) {
        changed = splitColumns_.remove(byteIndex) > 0 || changed;
    }
    if (changed) {
        rebuildVisibleColumns();
    }
    endResetModel();
    return changed;
}

bool ByteTableModel::removeSplitBitRange(int startBit, int endBit) {
    if (isBitDisplayMode()) {
        return false;
    }

    if (startBit > endBit) {
        return false;
    }

    bool changed = false;
    beginResetModel();

    const int startByteIndex = qMax(0, startBit / 8);
    const int endByteIndex = qMax(startByteIndex, endBit / 8);
    for (int byteIndex = startByteIndex; byteIndex <= endByteIndex; ++byteIndex) {
        if (!splitColumns_.contains(byteIndex)) {
            continue;
        }

        const int localStartBit = qMax(0, startBit - (byteIndex * 8));
        const int localEndBit = qMin(7, endBit - (byteIndex * 8));
        if (localStartBit > localEndBit) {
            continue;
        }

        const SplitColumnState splitState = splitColumns_.value(byteIndex);
        const QVector<SplitSegment> sourceSegments = currentSplitSegments(byteIndex);
        QVector<SplitSegment> remainingSegments;
        bool byteChanged = false;

        for (const SplitSegment& splitSegment : sourceSegments) {
            if (splitSegment.endBit < localStartBit || splitSegment.startBit > localEndBit) {
                remainingSegments.append(splitSegment);
                continue;
            }

            byteChanged = true;

            if (splitSegment.startBit < localStartBit) {
                SplitSegment leftSegment = splitSegment;
                leftSegment.endBit = localStartBit - 1;
                remainingSegments.append(leftSegment);
            }

            if (splitSegment.endBit > localEndBit) {
                SplitSegment rightSegment = splitSegment;
                rightSegment.startBit = localEndBit + 1;
                remainingSegments.append(rightSegment);
            }
        }

        if (!byteChanged) {
            continue;
        }

        if (remainingSegments.isEmpty()) {
            splitColumns_.remove(byteIndex);
        } else {
            applyCustomSplitSegments(
                byteIndex,
                splitState,
                remainingSegments,
                splitState.nextBinaryLabel,
                splitState.nextNibbleLabel
            );
        }
        changed = true;
    }

    if (changed) {
        rebuildVisibleColumns();
    }
    endResetModel();
    return changed;
}

std::optional<int> ByteTableModel::visibleDefinitionIndex(int visibleColumn) const {
    if (visibleColumn < 0 || visibleColumn >= visibleColumns_.size()) {
        return std::nullopt;
    }

    return definitionIndexForVisibleColumn(visibleColumns_.at(visibleColumn));
}

QVector<SplitPanelEntry> ByteTableModel::visibleSplitEntries() const {
    QVector<SplitPanelEntry> splitEntries;
    QList<int> sortedByteIndices = splitColumns_.keys();
    std::sort(sortedByteIndices.begin(), sortedByteIndices.end());

    for (int byteIndex : sortedByteIndices) {
        const SplitColumnState splitState = splitColumns_.value(byteIndex);
        if (splitState.type == QStringLiteral("custom")) {
            QVector<SplitSegment> splitSegments = splitState.segments;
            std::sort(splitSegments.begin(), splitSegments.end(), [](const SplitSegment& leftSegment, const SplitSegment& rightSegment) {
                return leftSegment.startBit < rightSegment.startBit;
            });

            QVector<SplitSegment> mergedSegments;
            for (const SplitSegment& splitSegment : splitSegments) {
                if (!mergedSegments.isEmpty()) {
                    SplitSegment& mergedSegment = mergedSegments.last();
                    if (mergedSegment.endBit + 1 == splitSegment.startBit
                        && mergedSegment.label == splitSegment.label
                        && normalizedDisplayFormat(mergedSegment.displayFormat)
                            == normalizedDisplayFormat(splitSegment.displayFormat)
                        && mergedSegment.colorName == splitSegment.colorName) {
                        mergedSegment.endBit = splitSegment.endBit;
                        continue;
                    }
                }
                mergedSegments.append(splitSegment);
            }

            for (const SplitSegment& splitSegment : mergedSegments) {
                SplitPanelEntry splitEntry;
                splitEntry.payloadByteIndex = byteIndex;
                splitEntry.startBit = byteIndex * 8 + splitSegment.startBit;
                splitEntry.endBit = byteIndex * 8 + splitSegment.endBit;
                splitEntry.label = splitSegment.label;
                splitEntry.displayFormat = normalizedDisplayFormat(splitSegment.displayFormat);
                splitEntry.colorName = splitSegment.colorName;
                splitEntries.append(splitEntry);
            }
            continue;
        }

        const QVector<SplitSegment> splitSegments = splitSegmentsForByte(byteIndex);
        if (splitSegments.isEmpty()) {
            continue;
        }

        SplitPanelEntry splitEntry;
        splitEntry.payloadByteIndex = byteIndex;
        splitEntry.startBit = byteIndex * 8 + splitSegments.first().startBit;
        splitEntry.endBit = byteIndex * 8 + splitSegments.last().endBit;
        splitEntry.label = splitState.label;
        splitEntry.displayFormat = normalizedDisplayFormat(splitSegments.first().displayFormat);
        splitEntry.colorName = splitState.colorName;
        splitEntries.append(splitEntry);
    }

    return splitEntries;
}

QString ByteTableModel::topHeaderLabelForVisibleColumn(int visibleColumn) const {
    if (visibleColumn < 0 || visibleColumn >= visibleColumns_.size()) {
        return {};
    }

    const features::columns::VisibleByteColumn& visibleColumnEntry = visibleColumns_.at(visibleColumn);
    if (isBitDisplayMode()) {
        if (visibleColumnEntry.definitionIndex >= 0) {
            const features::columns::ByteColumnDefinition* columnDefinition =
                definitionAtIndex(visibleColumnEntry.definitionIndex);
            if (columnDefinition != nullptr) {
                const QString labelText = columnDefinition->label.trimmed();
                if (!labelText.isEmpty()) {
                    return labelText;
                }
            }
        }

        const QString splitLabel = visibleColumnEntry.splitLabel.trimmed();
        if (!splitLabel.isEmpty()) {
            return splitLabel;
        }

        return formatRangeLabel(visibleColumnEntry.byteIndex, visibleColumnEntry.byteEndIndex);
    }

    if (visibleColumnEntry.definitionIndex >= 0) {
        const features::columns::ByteColumnDefinition* columnDefinition = definitionAtIndex(visibleColumnEntry.definitionIndex);
        if (columnDefinition != nullptr) {
            return columnDefinition->label.trimmed();
        }
        return {};
    }

    return visibleColumnEntry.splitLabel.trimmed();
}

QString ByteTableModel::bottomHeaderLabelForVisibleColumn(int visibleColumn) const {
    if (visibleColumn < 0 || visibleColumn >= visibleColumns_.size()) {
        return {};
    }

    const features::columns::VisibleByteColumn& visibleColumnEntry = visibleColumns_.at(visibleColumn);
    if (isBitDisplayMode()) {
        return QString::number(visibleColumnEntry.bitStart);
    }
    return formatRangeLabel(visibleColumnEntry.byteIndex, visibleColumnEntry.byteEndIndex);
}

QSet<int> ByteTableModel::plainByteTargetsForVisibleColumns(const QSet<int>& visibleColumns) const {
    return plainByteSplitTargets(visibleColumns);
}

QSet<int> ByteTableModel::splitByteTargetsForVisibleColumns(const QSet<int>& visibleColumns) const {
    QSet<int> splitByteTargets;
    for (int visibleColumnIndex : visibleColumns) {
        if (visibleColumnIndex < 0 || visibleColumnIndex >= visibleColumns_.size()) {
            continue;
        }
        const features::columns::VisibleByteColumn visibleColumn = visibleColumns_.at(visibleColumnIndex);
        if (!visibleColumn.splitLabel.isEmpty() || splitColumns_.contains(visibleColumn.byteIndex)) {
            splitByteTargets.insert(visibleColumn.byteIndex);
        }
    }
    return splitByteTargets;
}

bool ByteTableModel::selectionCanBecomeNibble(const QSet<int>& visibleColumns) const {
    if (isBitDisplayMode()) {
        return false;
    }

    const std::optional<SingleByteSelection> selection = singleByteSelection(visibleColumns);
    if (!selection.has_value() || selection->bitWidth != 4 || !splitColumns_.contains(selection->byteIndex)) {
        return false;
    }

    const QVector<SplitSegment> splitSegments = currentSplitSegments(selection->byteIndex);
    for (const SplitSegment& splitSegment : splitSegments) {
        if (normalizedDisplayFormat(splitSegment.displayFormat) != QStringLiteral("binary")) {
            continue;
        }
        if (splitSegment.startBit <= selection->startBit && selection->endBit <= splitSegment.endBit) {
            return true;
        }
    }

    return false;
}

bool ByteTableModel::selectionCanBecomeBinary(const QSet<int>& visibleColumns) const {
    if (isBitDisplayMode()) {
        return false;
    }

    const std::optional<SingleByteSelection> selection = singleByteSelection(visibleColumns);
    if (!selection.has_value() || selection->bitWidth != 4 || !splitColumns_.contains(selection->byteIndex)) {
        return false;
    }

    const QVector<SplitSegment> splitSegments = currentSplitSegments(selection->byteIndex);
    for (const SplitSegment& splitSegment : splitSegments) {
        if (normalizedDisplayFormat(splitSegment.displayFormat) != QStringLiteral("hex")) {
            continue;
        }
        if (splitSegment.startBit == selection->startBit && splitSegment.endBit == selection->endBit) {
            return true;
        }
    }

    return false;
}

bool ByteTableModel::convertSelectionToNibble(const QSet<int>& visibleColumns) {
    if (isBitDisplayMode()) {
        return false;
    }

    const std::optional<SingleByteSelection> selection = singleByteSelection(visibleColumns);
    if (!selection.has_value() || selection->bitWidth != 4) {
        return false;
    }

    const int byteIndex = selection->byteIndex;
    if (!splitColumns_.contains(byteIndex)) {
        return false;
    }

    const SplitColumnState splitState = splitColumns_.value(byteIndex);
    const QVector<SplitSegment> sourceSegments = currentSplitSegments(byteIndex);
    if (sourceSegments.isEmpty()) {
        return false;
    }

    SplitSegment targetSegment;
    bool foundTargetSegment = false;
    for (const SplitSegment& splitSegment : sourceSegments) {
        if (normalizedDisplayFormat(splitSegment.displayFormat) != QStringLiteral("binary")) {
            continue;
        }
        if (splitSegment.startBit <= selection->startBit && selection->endBit <= splitSegment.endBit) {
            targetSegment = splitSegment;
            foundTargetSegment = true;
            break;
        }
    }
    if (!foundTargetSegment) {
        return false;
    }

    int nextBinaryLabel = splitState.nextBinaryLabel;
    int nextNibbleLabel = splitState.nextNibbleLabel;
    QVector<SplitSegment> replacement;

    auto appendBinarySegment = [&](int startBit, int endBit) {
        if (startBit > endBit) {
            return;
        }
        SplitSegment splitSegment;
        splitSegment.startBit = startBit;
        splitSegment.endBit = endBit;
        splitSegment.displayFormat = QStringLiteral("binary");
        splitSegment.label = QStringLiteral("BIN %1").arg(nextBinaryLabel++);
        splitSegment.colorName = nextAutoSplitColorName(QStringLiteral("Sky"));
        replacement.append(splitSegment);
    };

    appendBinarySegment(targetSegment.startBit, selection->startBit - 1);

    SplitSegment nibbleSegment;
    nibbleSegment.startBit = selection->startBit;
    nibbleSegment.endBit = selection->endBit;
    nibbleSegment.displayFormat = QStringLiteral("hex");
    nibbleSegment.label = QStringLiteral("NIBBLE %1").arg(nextNibbleLabel++);
    nibbleSegment.colorName = nextAutoSplitColorName(QStringLiteral("Coral"));
    replacement.append(nibbleSegment);

    appendBinarySegment(selection->endBit + 1, targetSegment.endBit);

    beginResetModel();
    applyCustomSplitSegments(
        byteIndex,
        splitState,
        replacementSegments(sourceSegments, targetSegment.startBit, targetSegment.endBit, replacement),
        nextBinaryLabel,
        nextNibbleLabel
    );
    rebuildVisibleColumns();
    endResetModel();
    return true;
}

bool ByteTableModel::convertSelectionToBinary(const QSet<int>& visibleColumns) {
    if (isBitDisplayMode()) {
        return false;
    }

    const std::optional<SingleByteSelection> selection = singleByteSelection(visibleColumns);
    if (!selection.has_value() || selection->bitWidth != 4) {
        return false;
    }

    const int byteIndex = selection->byteIndex;
    if (!splitColumns_.contains(byteIndex)) {
        return false;
    }

    const SplitColumnState splitState = splitColumns_.value(byteIndex);
    const QVector<SplitSegment> sourceSegments = currentSplitSegments(byteIndex);
    if (sourceSegments.isEmpty()) {
        return false;
    }

    SplitSegment targetSegment;
    bool foundTargetSegment = false;
    for (const SplitSegment& splitSegment : sourceSegments) {
        if (normalizedDisplayFormat(splitSegment.displayFormat) != QStringLiteral("hex")) {
            continue;
        }
        if (splitSegment.startBit == selection->startBit && splitSegment.endBit == selection->endBit) {
            targetSegment = splitSegment;
            foundTargetSegment = true;
            break;
        }
    }
    if (!foundTargetSegment) {
        return false;
    }

    int nextBinaryLabel = splitState.nextBinaryLabel;
    QVector<SplitSegment> replacement;
    for (int bitIndex = selection->startBit; bitIndex <= selection->endBit; ++bitIndex) {
        SplitSegment splitSegment;
        splitSegment.startBit = bitIndex;
        splitSegment.endBit = bitIndex;
        splitSegment.displayFormat = QStringLiteral("binary");
        splitSegment.label = QStringLiteral("BIN %1").arg(nextBinaryLabel++);
        splitSegment.colorName = nextAutoSplitColorName(QStringLiteral("Sky"));
        replacement.append(splitSegment);
    }

    beginResetModel();
    applyCustomSplitSegments(
        byteIndex,
        splitState,
        replacementSegments(sourceSegments, targetSegment.startBit, targetSegment.endBit, replacement),
        nextBinaryLabel,
        splitState.nextNibbleLabel
    );
    rebuildVisibleColumns();
    endResetModel();
    return true;
}

bool ByteTableModel::visibleColumnsAreContiguous(const QSet<int>& visibleColumns) const {
    if (visibleColumns.isEmpty()) {
        return false;
    }

    QList<int> sortedColumns = visibleColumns.values();
    std::sort(sortedColumns.begin(), sortedColumns.end());

    int previousEndBit = -1;
    for (int visibleColumnIndex : sortedColumns) {
        if (visibleColumnIndex < 0 || visibleColumnIndex >= visibleColumns_.size()) {
            return false;
        }

        const features::columns::VisibleByteColumn visibleColumn = visibleColumns_.at(visibleColumnIndex);
        if (previousEndBit >= 0 && visibleColumn.absoluteStartBit != previousEndBit + 1) {
            return false;
        }
        previousEndBit = visibleColumn.absoluteEndBit;
    }

    return true;
}

bool ByteTableModel::constantColumnHighlightEnabled() const {
    return constantColumnHighlightEnabled_;
}

QHash<int, SplitColumnState> ByteTableModel::splitColumns() const {
    return splitColumns_;
}

ByteTableModel::DisplayMode ByteTableModel::displayMode() const {
    return displayMode_;
}

bool ByteTableModel::isBitDisplayMode() const {
    return displayMode_ == DisplayMode::Bit;
}

ByteTableModel::BitCellDisplayMode ByteTableModel::bitCellDisplayMode() const {
    return bitCellDisplayMode_;
}

QFont ByteTableModel::contentFont() const {
    return monospaceFont_;
}

void ByteTableModel::setConstantColumnHighlightEnabled(bool highlightEnabled) {
    if (constantColumnHighlightEnabled_ == highlightEnabled) {
        return;
    }

    constantColumnHighlightEnabled_ = highlightEnabled;
    invalidateConstantVisibleColumnCache(false);
    if (highlightEnabled) {
        scheduleConstantVisibleColumnCacheRebuild();
    }

    if (rowCount() <= 0 || columnCount() <= 0) {
        return;
    }

    emit dataChanged(
        index(0, 0),
        index(rowCount() - 1, columnCount() - 1),
        {Qt::BackgroundRole}
    );
}

void ByteTableModel::setCounterHighlightedVisibleColumns(const QSet<int>& counterVisibleColumns) {
    if (counterVisibleColumnIndices_ == counterVisibleColumns) {
        return;
    }

    counterVisibleColumnIndices_ = counterVisibleColumns;
    if (rowCount() <= 0 || columnCount() <= 0) {
        return;
    }

    emit dataChanged(
        index(0, 0),
        index(rowCount() - 1, columnCount() - 1),
        {Qt::BackgroundRole}
    );
}

void ByteTableModel::setDetectedFieldDefinitions(
    const QVector<features::columns::ByteColumnDefinition>& detectedFieldDefinitions
) {
    if (byteColumnDefinitionsEqual(detectedFieldDefinitions_, detectedFieldDefinitions)) {
        return;
    }

    beginResetModel();
    detectedFieldDefinitions_ = detectedFieldDefinitions;
    rebuildVisibleColumns();
    endResetModel();
}

void ByteTableModel::setSplitColumns(const QHash<int, SplitColumnState>& splitColumns) {
    beginResetModel();
    splitColumns_ = splitColumns;
    rebuildVisibleColumns();
    endResetModel();
}

void ByteTableModel::setDisplayMode(DisplayMode displayMode) {
    if (displayMode_ == displayMode) {
        return;
    }

    beginResetModel();
    displayMode_ = displayMode;
    rebuildVisibleColumns();
    endResetModel();
}

void ByteTableModel::setBitCellDisplayMode(BitCellDisplayMode bitCellDisplayMode) {
    if (bitCellDisplayMode_ == bitCellDisplayMode) {
        return;
    }

    bitCellDisplayMode_ = bitCellDisplayMode;
    if (!isBitDisplayMode() || rowCount() <= 0 || columnCount() <= 0) {
        return;
    }

    emit dataChanged(index(0, 0), index(rowCount() - 1, columnCount() - 1));
}

void ByteTableModel::setContentFontPixelSize(int pixelSize) {
    const int normalizedPixelSize = qMax(1, pixelSize);
    if (monospaceFont_.pixelSize() == normalizedPixelSize) {
        return;
    }

    monospaceFont_.setPixelSize(normalizedPixelSize);
    if (rowCount() <= 0 || columnCount() <= 0) {
        return;
    }

    emit dataChanged(
        index(0, 0),
        index(rowCount() - 1, columnCount() - 1),
        {Qt::FontRole}
    );
}

void ByteTableModel::setPatternHighlightRanges(
    const QVector<QPair<qsizetype, qsizetype>>& patternHighlightRanges
) {
    QVector<QPair<qsizetype, qsizetype>> normalizedRanges;
    normalizedRanges.reserve(patternHighlightRanges.size());
    for (const QPair<qsizetype, qsizetype>& patternHighlightRange : patternHighlightRanges) {
        if (patternHighlightRange.second < patternHighlightRange.first) {
            continue;
        }
        normalizedRanges.append(patternHighlightRange);
    }

    std::sort(
        normalizedRanges.begin(),
        normalizedRanges.end(),
        [](const QPair<qsizetype, qsizetype>& leftRange, const QPair<qsizetype, qsizetype>& rightRange) {
            if (leftRange.first != rightRange.first) {
                return leftRange.first < rightRange.first;
            }
            return leftRange.second < rightRange.second;
        }
    );

    QVector<QPair<qsizetype, qsizetype>> mergedRanges;
    mergedRanges.reserve(normalizedRanges.size());
    for (const QPair<qsizetype, qsizetype>& normalizedRange : normalizedRanges) {
        if (mergedRanges.isEmpty() || normalizedRange.first > (mergedRanges.last().second + 1)) {
            mergedRanges.append(normalizedRange);
            continue;
        }

        mergedRanges.last().second = qMax(mergedRanges.last().second, normalizedRange.second);
    }

    if (patternHighlightRanges_ == mergedRanges) {
        return;
    }

    patternHighlightRanges_ = mergedRanges;
    if (rowCount() <= 0 || columnCount() <= 0) {
        return;
    }

    emit dataChanged(
        index(0, 0),
        index(rowCount() - 1, columnCount() - 1),
        {Qt::BackgroundRole}
    );
}

void ByteTableModel::reload() {
    beginResetModel();
    rebuildVisibleColumns();
    endResetModel();
}

void ByteTableModel::invalidateConstantVisibleColumnCache(bool notifyDataChanged) {
    ++constantHighlightRequestId_;
    const bool hadCachedHighlight = !constantVisibleColumnIndices_.isEmpty();
    constantVisibleColumnIndices_.clear();

    if (!notifyDataChanged || !hadCachedHighlight || rowCount() <= 0 || columnCount() <= 0) {
        return;
    }

    emit dataChanged(
        index(0, 0),
        index(rowCount() - 1, columnCount() - 1),
        {Qt::BackgroundRole}
    );
}

void ByteTableModel::scheduleConstantVisibleColumnCacheRebuild() {
    if (!constantColumnHighlightEnabled_) {
        return;
    }
    if (constantHighlightWatcher_ == nullptr) {
        return;
    }
    if (dataSource_ == nullptr || frameLayout_ == nullptr || visibleColumns_.isEmpty()) {
        return;
    }
    if (constantHighlightWatcher_->isRunning()) {
        return;
    }

    startConstantVisibleColumnCacheRebuild();
}

void ByteTableModel::startConstantVisibleColumnCacheRebuild() {
    if (!constantColumnHighlightEnabled_) {
        return;
    }
    if (constantHighlightWatcher_ == nullptr || constantHighlightWatcher_->isRunning()) {
        return;
    }
    if (dataSource_ == nullptr || frameLayout_ == nullptr || visibleColumns_.isEmpty()) {
        return;
    }

    activeConstantHighlightRequestId_ = constantHighlightRequestId_;
    const data::ByteDataSource dataSourceSnapshot = *dataSource_;
    const features::framing::FrameLayout frameLayoutSnapshot = *frameLayout_;
    const QVector<features::columns::VisibleByteColumn> visibleColumnsSnapshot = visibleColumns_;
    constantHighlightWatcher_->setFuture(QtConcurrent::run(
        [dataSourceSnapshot, frameLayoutSnapshot, visibleColumnsSnapshot]() {
            return constantVisibleColumnIndicesForSnapshot(
                dataSourceSnapshot,
                frameLayoutSnapshot,
                visibleColumnsSnapshot
            );
        }
    ));
}

int ByteTableModel::visibleColumnIndexForModelColumn(int col) const {
    if (col < 0) {
        return -1;
    }

    return hasFrameLengthColumn() ? col - 1 : col;
}

const features::columns::ByteColumnDefinition* ByteTableModel::definitionAtIndex(int definitionIndex) const {
    if (definitionIndex < 0 || definitionIndex >= effectiveColumnDefinitions_.size()) {
        return nullptr;
    }
    return &effectiveColumnDefinitions_.at(definitionIndex);
}

std::optional<int> ByteTableModel::definitionIndexForVisibleColumn(
    const features::columns::VisibleByteColumn& visibleColumn
) const {
    if (visibleColumn.definitionIndex < 0) {
        return std::nullopt;
    }

    const int userDefinitionCount = columnDefinitions_ != nullptr ? columnDefinitions_->size() : 0;
    if (visibleColumn.definitionIndex >= userDefinitionCount) {
        return std::nullopt;
    }
    return visibleColumn.definitionIndex;
}

QString ByteTableModel::formatVisibleColumnDisplayText(
    int row,
    const features::columns::VisibleByteColumn& visibleColumn
) const {
    if (!hasDisplayValue(row, visibleColumn)) {
        return {};
    }

    if (isBitDisplayMode()) {
        const QByteArray rowBits = rowBitsForVisibleColumn(row, visibleColumn);
        if (rowBits.isEmpty()) {
            return {};
        }
        return rowBits.at(0) != 0 ? QStringLiteral("1") : QStringLiteral("0");
    }

    if (visibleColumn.definitionIndex >= 0) {
        const features::columns::ByteColumnDefinition* columnDefinition = definitionAtIndex(visibleColumn.definitionIndex);
        if (columnDefinition == nullptr) {
            return {};
        }
        if (columnDefinition->unit == QStringLiteral("byte")) {
            return formatBytes(
                rowBytesSlice(row, columnDefinition->startByte, columnDefinition->byteCount()),
                columnDefinition->displayFormat
            );
        }
        return formatBits(
            rowBitsSlice(row, columnDefinition->startBit, qMax(1, columnDefinition->totalBits)),
            columnDefinition->displayFormat
        );
    }

    return formatBits(rowBitsForVisibleColumn(row, visibleColumn), visibleColumn.splitDisplayFormat);
}

QString ByteTableModel::formatVisibleColumnToolTip(
    int row,
    qsizetype startBit,
    const features::columns::VisibleByteColumn& visibleColumn
) const {
    if (!hasDisplayValue(row, visibleColumn)) {
        return QStringLiteral("No data in this frame position.");
    }

    QString toolTipText = QStringLiteral("Start bit %1").arg(startBit);
    if (visibleColumn.definitionIndex >= 0) {
        const features::columns::ByteColumnDefinition* columnDefinition = definitionAtIndex(visibleColumn.definitionIndex);
        if (columnDefinition != nullptr) {
            toolTipText += QStringLiteral(" | Column %1 | Format %2")
                .arg(columnDefinition->label.isEmpty() ? QStringLiteral("(unnamed)") : columnDefinition->label)
                .arg(columnDefinition->displayFormat);
        }
    } else if (!visibleColumn.splitLabel.isEmpty()) {
        toolTipText += QStringLiteral(" | Split %1").arg(visibleColumn.splitLabel);
    }
    toolTipText += QStringLiteral(" | Value %1").arg(formatVisibleColumnDisplayText(row, visibleColumn));
    return toolTipText;
}

QColor ByteTableModel::backgroundForVisibleColumn(
    int visibleColumnIndex,
    const features::columns::VisibleByteColumn& visibleColumn
) const {
    const features::columns::ByteColumnDefinition* columnDefinition =
        visibleColumn.definitionIndex >= 0 ? definitionAtIndex(visibleColumn.definitionIndex) : nullptr;
    QColor backgroundColor;
    if (columnDefinition != nullptr) {
        backgroundColor = features::columns::colorForName(columnDefinition->colorName);
    } else if (!visibleColumn.splitColorName.trimmed().isEmpty()
        && visibleColumn.splitColorName.trimmed() != QStringLiteral("None")) {
        backgroundColor = features::columns::colorForName(visibleColumn.splitColorName.trimmed());
    }

    if (constantColumnHighlightEnabled_
        && constantVisibleColumnIndices_.contains(visibleColumnIndex)) {
        return blendHighlightColor(backgroundColor, kConstantHighlightColor, backgroundColor.isValid() ? 0.62 : 1.0);
    }

    if (counterVisibleColumnIndices_.contains(visibleColumnIndex)) {
        return blendHighlightColor(backgroundColor, kCounterHighlightColor, backgroundColor.isValid() ? 0.62 : 1.0);
    }

    return backgroundColor;
}

bool ByteTableModel::hasDisplayValue(int row, const features::columns::VisibleByteColumn& visibleColumn) const {
    return visibleColumn.absoluteEndBit < rowLengthBits(row);
}

QVector<SplitSegment> ByteTableModel::splitSegmentsForByte(int byteIndex) const {
    if (!splitColumns_.contains(byteIndex)) {
        return {};
    }

    const SplitColumnState splitState = splitColumns_.value(byteIndex);
    if (splitState.type == QStringLiteral("custom")) {
        return splitState.segments;
    }

    QVector<SplitSegment> splitSegments;
    if (splitState.type == QStringLiteral("binary")) {
        for (int bitIndex = 0; bitIndex < 8; ++bitIndex) {
            SplitSegment splitSegment;
            splitSegment.startBit = bitIndex;
            splitSegment.endBit = bitIndex;
            splitSegment.displayFormat = QStringLiteral("binary");
            splitSegment.label = splitState.label;
            splitSegment.colorName = splitState.colorName;
            splitSegments.append(splitSegment);
        }
        return splitSegments;
    }

    if (splitState.type == QStringLiteral("nibble")) {
        SplitSegment upperNibble;
        upperNibble.startBit = 0;
        upperNibble.endBit = 3;
        upperNibble.displayFormat = QStringLiteral("hex");
        upperNibble.label = splitState.label;
        upperNibble.colorName = splitState.colorName;
        splitSegments.append(upperNibble);

        SplitSegment lowerNibble;
        lowerNibble.startBit = 4;
        lowerNibble.endBit = 7;
        lowerNibble.displayFormat = QStringLiteral("hex");
        lowerNibble.label = splitState.label;
        lowerNibble.colorName = splitState.colorName;
        splitSegments.append(lowerNibble);
        return splitSegments;
    }

    return splitState.segments;
}

int ByteTableModel::nextSplitLabelIndex(const QString& prefix) const {
    int nextIndex = 0;
    for (auto splitIterator = splitColumns_.cbegin(); splitIterator != splitColumns_.cend(); ++splitIterator) {
        const SplitColumnState& splitState = splitIterator.value();
        QStringList candidateLabels;
        candidateLabels.append(splitState.label);
        for (const SplitSegment& splitSegment : splitState.segments) {
            candidateLabels.append(splitSegment.label);
        }

        for (const QString& candidateLabel : candidateLabels) {
            const QString trimmedLabel = candidateLabel.trimmed();
            if (!trimmedLabel.startsWith(prefix + QLatin1Char(' '))) {
                continue;
            }

            bool parsed = false;
            const int labelIndex = trimmedLabel.mid(prefix.size() + 1).toInt(&parsed);
            if (parsed) {
                nextIndex = qMax(nextIndex, labelIndex + 1);
            }
        }
    }

    return nextIndex;
}

QString ByteTableModel::nextAutoSplitColorName(
    const QString& preferredColor,
    const QSet<QString>& excludedColors
) const {
    static const std::array<QString, 6> autoColorSequence = {
        QStringLiteral("Sky"),
        QStringLiteral("Coral"),
        QStringLiteral("Mint"),
        QStringLiteral("Gold"),
        QStringLiteral("Lilac"),
        QStringLiteral("Sunshine"),
    };

    std::array<int, autoColorSequence.size()> usedCounts{};
    const auto colorIndexForName = [](QStringView colorName) {
        for (size_t colorIndex = 0; colorIndex < autoColorSequence.size(); ++colorIndex) {
            if (autoColorSequence[colorIndex] == colorName) {
                return static_cast<int>(colorIndex);
            }
        }
        return -1;
    };

    if (columnDefinitions_ != nullptr) {
        for (const features::columns::ByteColumnDefinition& columnDefinition : *columnDefinitions_) {
            const int colorIndex = colorIndexForName(columnDefinition.colorName);
            if (colorIndex >= 0) {
                usedCounts[static_cast<size_t>(colorIndex)] += 1;
            }
        }
    }

    for (auto splitIterator = splitColumns_.cbegin(); splitIterator != splitColumns_.cend(); ++splitIterator) {
        const SplitColumnState& splitState = splitIterator.value();
        const int splitStateColorIndex = colorIndexForName(splitState.colorName);
        if (splitStateColorIndex >= 0) {
            usedCounts[static_cast<size_t>(splitStateColorIndex)] += 1;
        }
        for (const SplitSegment& splitSegment : splitState.segments) {
            const int splitSegmentColorIndex = colorIndexForName(splitSegment.colorName);
            if (splitSegmentColorIndex >= 0) {
                usedCounts[static_cast<size_t>(splitSegmentColorIndex)] += 1;
            }
        }
    }

    int preferredIndex = 0;
    const int matchedPreferredIndex = colorIndexForName(preferredColor);
    if (matchedPreferredIndex >= 0) {
        preferredIndex = matchedPreferredIndex;
    }

    int bestIndex = -1;
    int bestCount = std::numeric_limits<int>::max();
    int bestDistance = std::numeric_limits<int>::max();
    for (size_t colorIndex = 0; colorIndex < autoColorSequence.size(); ++colorIndex) {
        if (excludedColors.contains(autoColorSequence[colorIndex])) {
            continue;
        }

        const int usedCount = usedCounts[colorIndex];
        const int colorDistance = (static_cast<int>(colorIndex) - preferredIndex + static_cast<int>(autoColorSequence.size()))
            % static_cast<int>(autoColorSequence.size());
        if (usedCount < bestCount || (usedCount == bestCount && colorDistance < bestDistance)) {
            bestIndex = static_cast<int>(colorIndex);
            bestCount = usedCount;
            bestDistance = colorDistance;
        }
    }

    if (bestIndex < 0) {
        bestIndex = 0;
    }
    return autoColorSequence[static_cast<size_t>(bestIndex)];
}

QSet<int> ByteTableModel::plainByteSplitTargets(const QSet<int>& visibleColumns) const {
    QSet<int> byteTargets;
    for (int visibleColumnIndex : visibleColumns) {
        if (visibleColumnIndex < 0 || visibleColumnIndex >= visibleColumns_.size()) {
            continue;
        }

        const features::columns::VisibleByteColumn visibleColumn = visibleColumns_.at(visibleColumnIndex);
        if (visibleColumn.definitionIndex >= 0
            || visibleColumn.isUndefined
            || !visibleColumn.splitLabel.isEmpty()
            || visibleColumn.bitStart != 0
            || visibleColumn.bitEnd != 7) {
            continue;
        }
        byteTargets.insert(visibleColumn.byteIndex);
    }
    return byteTargets;
}

std::optional<QPair<int, int>> ByteTableModel::definitionBitSpan(
    const features::columns::ByteColumnDefinition& definition
) const {
    const int widthBytes = displayWidthBytes();
    if (widthBytes <= 0) {
        return std::nullopt;
    }

    if (definition.unit == QStringLiteral("bit")) {
        const int totalBits = qMax(1, definition.totalBits);
        const int startBit = qMax(0, definition.startBit);
        const int endBit = qMin(definition.startBit + totalBits - 1, widthBytes * 8 - 1);
        if (endBit < startBit) {
            return std::nullopt;
        }
        return QPair<int, int>(startBit, endBit);
    }

    const int startByte = qMax(0, definition.startByte);
    const int endByte = qMin(definition.endByte, widthBytes - 1);
    if (endByte < startByte) {
        return std::nullopt;
    }
    return QPair<int, int>(startByte * 8, (endByte + 1) * 8 - 1);
}

features::columns::VisibleByteColumn ByteTableModel::buildVisibleDefinitionColumn(
    const features::columns::ByteColumnDefinition& definition,
    int definitionIndex
) const {
    const std::optional<QPair<int, int>> bitSpan = definitionBitSpan(definition);
    if (!bitSpan.has_value()) {
        return {};
    }

    features::columns::VisibleByteColumn visibleColumn;
    visibleColumn.byteIndex = bitSpan->first / 8;
    visibleColumn.bitStart = bitSpan->first % 8;
    visibleColumn.byteEndIndex = bitSpan->second / 8;
    visibleColumn.bitEnd = bitSpan->second % 8;
    visibleColumn.absoluteStartBit = bitSpan->first;
    visibleColumn.absoluteEndBit = bitSpan->second;
    visibleColumn.definitionIndex = definitionIndex;
    return visibleColumn;
}

QString ByteTableModel::formatRangeLabel(int startValue, int endValue) const {
    return startValue == endValue
        ? core::formatByteHeaderLabel(startValue)
        : QStringLiteral("%1-%2")
              .arg(core::formatByteHeaderLabel(startValue))
              .arg(core::formatByteHeaderLabel(endValue));
}

void ByteTableModel::rebuildVisibleColumns() {
    visibleColumns_.clear();
    byteColumnStarts_.clear();
    byteColumnCounts_.clear();
    counterVisibleColumnIndices_.clear();
    invalidateConstantVisibleColumnCache(false);
    effectiveColumnDefinitions_.clear();

    if (dataSource_ == nullptr || frameLayout_ == nullptr) {
        return;
    }

    const int widthBytes = displayWidthBytes();
    if (widthBytes <= 0) {
        return;
    }

    if (columnDefinitions_ != nullptr) {
        effectiveColumnDefinitions_ = *columnDefinitions_;
    }
    for (const features::columns::ByteColumnDefinition& detectedFieldDefinition : detectedFieldDefinitions_) {
        effectiveColumnDefinitions_.append(detectedFieldDefinition);
    }

    if (isBitDisplayMode()) {
        const int totalBitCount = frameLayout_->isFramed()
            ? (
                frameLayout_->padFramedBitDisplayToByteBoundary()
                    ? widthBytes * 8
                    : static_cast<int>(qMax<qsizetype>(0, frameLayout_->frameMaxLengthBits()))
            )
            : static_cast<int>(qMax<qsizetype>(0, frameLayout_->rawRowWidthBits()));
        QVector<int> definitionIndexByBit(totalBitCount, -1);
        QVector<QString> splitLabelByBit(totalBitCount);
        QVector<QString> splitColorByBit(totalBitCount);
        QVector<QString> splitDisplayFormatByBit(totalBitCount);

        for (int definitionIndex = 0; definitionIndex < effectiveColumnDefinitions_.size(); ++definitionIndex) {
            const std::optional<QPair<int, int>> bitSpan =
                definitionBitSpan(effectiveColumnDefinitions_.at(definitionIndex));
            if (!bitSpan.has_value()) {
                continue;
            }

            for (int absoluteBit = bitSpan->first; absoluteBit <= bitSpan->second; ++absoluteBit) {
                if (absoluteBit < 0 || absoluteBit >= totalBitCount) {
                    continue;
                }
                if (definitionIndexByBit[absoluteBit] < 0) {
                    definitionIndexByBit[absoluteBit] = definitionIndex;
                }
            }
        }

        for (int byteIndex = 0; byteIndex < widthBytes; ++byteIndex) {
            const QVector<SplitSegment> splitSegments = splitSegmentsForByte(byteIndex);
            for (const SplitSegment& splitSegment : splitSegments) {
                for (int bitIndex = splitSegment.startBit; bitIndex <= splitSegment.endBit; ++bitIndex) {
                    const int absoluteBit = (byteIndex * 8) + bitIndex;
                    if (absoluteBit < 0 || absoluteBit >= totalBitCount || definitionIndexByBit[absoluteBit] >= 0) {
                        continue;
                    }

                    splitLabelByBit[absoluteBit] = splitSegment.label.trimmed();
                    splitColorByBit[absoluteBit] = splitSegment.colorName.trimmed();
                    splitDisplayFormatByBit[absoluteBit] = normalizedDisplayFormat(splitSegment.displayFormat);
                }
            }
        }

        visibleColumns_.reserve(totalBitCount);
        for (int absoluteBit = 0; absoluteBit < totalBitCount; ++absoluteBit) {
            features::columns::VisibleByteColumn visibleColumn;
            visibleColumn.byteIndex = absoluteBit / 8;
            visibleColumn.byteEndIndex = visibleColumn.byteIndex;
            visibleColumn.bitStart = absoluteBit % 8;
            visibleColumn.bitEnd = visibleColumn.bitStart;
            visibleColumn.absoluteStartBit = absoluteBit;
            visibleColumn.absoluteEndBit = absoluteBit;
            visibleColumn.definitionIndex = definitionIndexByBit.at(absoluteBit);
            visibleColumn.splitLabel = splitLabelByBit.at(absoluteBit);
            visibleColumn.splitColorName = splitColorByBit.at(absoluteBit).isEmpty()
                ? QStringLiteral("None")
                : splitColorByBit.at(absoluteBit);
            visibleColumn.splitDisplayFormat = splitDisplayFormatByBit.at(absoluteBit).isEmpty()
                ? QStringLiteral("binary")
                : splitDisplayFormatByBit.at(absoluteBit);
            visibleColumns_.append(visibleColumn);
        }

        rebuildByteColumnIndexMap();
        if (constantColumnHighlightEnabled_) {
            scheduleConstantVisibleColumnCacheRebuild();
        }
        return;
    }

    QVector<DefinitionSpanInfo> definitionSpans;
    QVector<QVector<int>> definitionsStartingByByte(widthBytes);
    QVector<QVector<QPair<int, int>>> definitionRangesByByte(widthBytes);
    if (!effectiveColumnDefinitions_.isEmpty()) {
        definitionSpans.reserve(effectiveColumnDefinitions_.size());
        for (int definitionIndex = 0; definitionIndex < effectiveColumnDefinitions_.size(); ++definitionIndex) {
            const features::columns::ByteColumnDefinition& definition = effectiveColumnDefinitions_.at(definitionIndex);
            const std::optional<QPair<int, int>> bitSpan = definitionBitSpan(definition);
            if (!bitSpan.has_value()) {
                continue;
            }

            DefinitionSpanInfo definitionSpan;
            definitionSpan.definitionIndex = definitionIndex;
            definitionSpan.startBit = bitSpan->first;
            definitionSpan.endBit = bitSpan->second;
            definitionSpan.startByte = bitSpan->first / 8;
            definitionSpan.endByte = bitSpan->second / 8;
            definitionSpan.visibleColumn = buildVisibleDefinitionColumn(definition, definitionIndex);
            definitionSpans.append(definitionSpan);

            if (definitionSpan.startByte >= 0 && definitionSpan.startByte < widthBytes) {
                definitionsStartingByByte[definitionSpan.startByte].append(definitionSpans.size() - 1);
            }

            for (int byteIndex = qMax(0, definitionSpan.startByte); byteIndex <= qMin(widthBytes - 1, definitionSpan.endByte); ++byteIndex) {
                const int byteStartBit = byteIndex * 8;
                definitionRangesByByte[byteIndex].append(
                    qMakePair(
                        qMax(0, definitionSpan.startBit - byteStartBit),
                        qMin(7, definitionSpan.endBit - byteStartBit)
                    )
                );
            }
        }
    }

    QVector<QVector<QPair<int, int>>> undefinedRangesByByte(widthBytes);
    for (int byteIndex = 0; byteIndex < widthBytes; ++byteIndex) {
        QVector<QPair<int, int>>& definitionRanges = definitionRangesByByte[byteIndex];
        if (definitionRanges.isEmpty()) {
            continue;
        }

        std::sort(definitionRanges.begin(), definitionRanges.end(), [](const auto& leftRange, const auto& rightRange) {
            return leftRange.first < rightRange.first;
        });

        QVector<QPair<int, int>>& undefinedRanges = undefinedRangesByByte[byteIndex];
        int currentBit = 0;
        for (const QPair<int, int>& definitionRange : definitionRanges) {
            if (currentBit < definitionRange.first) {
                undefinedRanges.append(qMakePair(currentBit, definitionRange.first - 1));
            }
            currentBit = qMax(currentBit, definitionRange.second + 1);
        }
        if (currentBit <= 7) {
            undefinedRanges.append(qMakePair(currentBit, 7));
        }
    }

    for (int byteIndex = 0; byteIndex < widthBytes; ++byteIndex) {
        const bool byteCoveredByDefinition = !definitionRangesByByte[byteIndex].isEmpty();
        QVector<features::columns::VisibleByteColumn> byteVisibleColumns;
        const QVector<int>& definitionIndexes = definitionsStartingByByte[byteIndex];
        for (int definitionSpanIndex : definitionIndexes) {
            if (definitionSpanIndex < 0 || definitionSpanIndex >= definitionSpans.size()) {
                continue;
            }
            byteVisibleColumns.append(definitionSpans.at(definitionSpanIndex).visibleColumn);
        }

        const QVector<QPair<int, int>> baseRanges = definitionRangesByByte[byteIndex].isEmpty()
            ? QVector<QPair<int, int>>{qMakePair(0, 7)}
            : undefinedRangesByByte[byteIndex];

        const QVector<SplitSegment> splitSegments = splitSegmentsForByte(byteIndex);
        for (const QPair<int, int>& baseRange : baseRanges) {
            bool appendedSplitColumn = false;
            for (const SplitSegment& splitSegment : splitSegments) {
                const int segmentStartBit = qMax(baseRange.first, splitSegment.startBit);
                const int segmentEndBit = qMin(baseRange.second, splitSegment.endBit);
                if (segmentStartBit > segmentEndBit) {
                    continue;
                }

                appendedSplitColumn = true;
                if (normalizedDisplayFormat(splitSegment.displayFormat) == QStringLiteral("binary")) {
                    for (int bitIndex = segmentStartBit; bitIndex <= segmentEndBit; ++bitIndex) {
                        features::columns::VisibleByteColumn visibleColumn;
                        visibleColumn.byteIndex = byteIndex;
                        visibleColumn.byteEndIndex = byteIndex;
                        visibleColumn.bitStart = bitIndex;
                        visibleColumn.bitEnd = bitIndex;
                        visibleColumn.absoluteStartBit = byteIndex * 8 + bitIndex;
                        visibleColumn.absoluteEndBit = byteIndex * 8 + bitIndex;
                        visibleColumn.splitLabel = splitSegment.label;
                        visibleColumn.splitColorName = splitSegment.colorName;
                        visibleColumn.splitDisplayFormat = QStringLiteral("binary");
                        byteVisibleColumns.append(visibleColumn);
                    }
                    continue;
                }

                features::columns::VisibleByteColumn visibleColumn;
                visibleColumn.byteIndex = byteIndex;
                visibleColumn.byteEndIndex = byteIndex;
                visibleColumn.bitStart = segmentStartBit;
                visibleColumn.bitEnd = segmentEndBit;
                visibleColumn.absoluteStartBit = byteIndex * 8 + segmentStartBit;
                visibleColumn.absoluteEndBit = byteIndex * 8 + segmentEndBit;
                visibleColumn.splitLabel = splitSegment.label;
                visibleColumn.splitColorName = splitSegment.colorName;
                visibleColumn.splitDisplayFormat = QStringLiteral("hex");
                byteVisibleColumns.append(visibleColumn);
            }

            if (!appendedSplitColumn) {
                features::columns::VisibleByteColumn visibleColumn;
                visibleColumn.byteIndex = byteIndex;
                visibleColumn.byteEndIndex = byteIndex;
                visibleColumn.bitStart = baseRange.first;
                visibleColumn.bitEnd = baseRange.second;
                visibleColumn.absoluteStartBit = byteIndex * 8 + baseRange.first;
                visibleColumn.absoluteEndBit = byteIndex * 8 + baseRange.second;
                visibleColumn.isUndefined = byteCoveredByDefinition;
                byteVisibleColumns.append(visibleColumn);
            }
        }

        std::sort(byteVisibleColumns.begin(), byteVisibleColumns.end(), [](const auto& leftColumn, const auto& rightColumn) {
            if (leftColumn.absoluteStartBit != rightColumn.absoluteStartBit) {
                return leftColumn.absoluteStartBit < rightColumn.absoluteStartBit;
            }
            return leftColumn.absoluteEndBit < rightColumn.absoluteEndBit;
        });
        visibleColumns_ += byteVisibleColumns;
    }

    rebuildByteColumnIndexMap();
    if (constantColumnHighlightEnabled_) {
        scheduleConstantVisibleColumnCacheRebuild();
    }
}

void ByteTableModel::rebuildByteColumnIndexMap() {
    const int widthBytes = displayWidthBytes();
    if (widthBytes <= 0) {
        byteColumnStarts_.clear();
        byteColumnCounts_.clear();
        return;
    }

    byteColumnStarts_.fill(-1, widthBytes);
    byteColumnCounts_.fill(0, widthBytes);

    for (int visibleColumnIndex = 0; visibleColumnIndex < visibleColumns_.size(); ++visibleColumnIndex) {
        const features::columns::VisibleByteColumn& visibleColumn = visibleColumns_.at(visibleColumnIndex);
        const int startByteIndex = qBound(0, visibleColumn.byteIndex, widthBytes - 1);
        const int endByteIndex = qBound(0, visibleColumn.byteEndIndex, widthBytes - 1);
        for (int byteIndex = startByteIndex; byteIndex <= endByteIndex; ++byteIndex) {
            if (byteColumnStarts_.at(byteIndex) < 0) {
                byteColumnStarts_[byteIndex] = visibleColumnIndex;
            }
            byteColumnCounts_[byteIndex] += 1;
        }
    }
}

qsizetype ByteTableModel::cellStartBit(int row, int col) const {
    const int visibleColumnIndex = visibleColumnIndexForModelColumn(col);
    if (visibleColumnIndex < 0 || visibleColumnIndex >= visibleColumns_.size()) {
        return -1;
    }

    return rowStartBit(row) + visibleColumns_.at(visibleColumnIndex).absoluteStartBit;
}

qsizetype ByteTableModel::rowStartBit(int row) const {
    if (dataSource_ == nullptr || frameLayout_ == nullptr) {
        return -1;
    }
    return frameLayout_->rowStartBit(*dataSource_, row);
}

qsizetype ByteTableModel::rowLengthBits(int row) const {
    if (dataSource_ == nullptr || frameLayout_ == nullptr) {
        return 0;
    }
    return frameLayout_->rowLengthBits(*dataSource_, row);
}

QByteArray ByteTableModel::rowBitsSlice(int row, int startRelativeBit, int bitCount) const {
    QByteArray bitValues;
    if (dataSource_ == nullptr || frameLayout_ == nullptr || bitCount <= 0) {
        return bitValues;
    }

    const qsizetype rowBitLength = rowLengthBits(row);
    if (startRelativeBit < 0 || startRelativeBit >= rowBitLength) {
        return bitValues;
    }

    const qsizetype availableBitCount = qMin<qsizetype>(bitCount, rowBitLength - startRelativeBit);
    const qsizetype absoluteStartBit = rowStartBit(row) + startRelativeBit;
    return dataSource_->bitRange(absoluteStartBit, availableBitCount);
}

QByteArray ByteTableModel::rowBitsForVisibleColumn(
    int row,
    const features::columns::VisibleByteColumn& visibleColumn
) const {
    return rowBitsSlice(row, visibleColumn.absoluteStartBit, visibleColumn.bitWidth());
}

QByteArray ByteTableModel::rowBytesSlice(int row, int startByte, int byteCount) const {
    QByteArray rowBytes;
    if (dataSource_ == nullptr || frameLayout_ == nullptr || byteCount <= 0) {
        return rowBytes;
    }

    const qsizetype rowBitLength = rowLengthBits(row);
    const qsizetype startRelativeBit = static_cast<qsizetype>(startByte) * 8;
    if (startRelativeBit < 0 || startRelativeBit >= rowBitLength) {
        return rowBytes;
    }

    const qsizetype availableBitCount = qMin<qsizetype>(static_cast<qsizetype>(byteCount) * 8, rowBitLength - startRelativeBit);
    const int fullByteCount = static_cast<int>(availableBitCount / 8);
    if (fullByteCount <= 0) {
        return rowBytes;
    }

    const qsizetype absoluteStartBit = rowStartBit(row) + startRelativeBit;
    return dataSource_->byteRangeAtBitOffset(absoluteStartBit, fullByteCount);
}

QString ByteTableModel::formatRowHeaderText(int row) const {
    if (frameLayout_ == nullptr || dataSource_ == nullptr) {
        return {};
    }

    if (frameLayout_->isFramed()) {
        return QString::number(row);
    }

    return formatBitStartLabel(frameLayout_->rowStartBit(*dataSource_, row));
}

QString ByteTableModel::formatBytes(const QByteArray& rowBytes, const QString& displayFormat) const {
    if (rowBytes.isEmpty()) {
        return {};
    }

    const QString normalizedFormat = normalizedDisplayFormat(displayFormat);
    if (normalizedFormat == QStringLiteral("binary")) {
        QString binaryText;
        binaryText.reserve(rowBytes.size() * 8);
        for (unsigned char byteValue : rowBytes) {
            for (int bitShift = 7; bitShift >= 0; --bitShift) {
                binaryText.append(((byteValue >> bitShift) & 0x01) != 0 ? QLatin1Char('1') : QLatin1Char('0'));
            }
        }
        return binaryText;
    }

    if (normalizedFormat == QStringLiteral("decimal")) {
        quint64 numericValue = 0;
        for (unsigned char byteValue : rowBytes) {
            numericValue = (numericValue << 8) | byteValue;
        }
        return QString::number(numericValue);
    }

    if (normalizedFormat == QStringLiteral("ascii")) {
        QString asciiText;
        asciiText.reserve(rowBytes.size());
        for (unsigned char byteValue : rowBytes) {
            asciiText.append(core::formatPrintableAscii(byteValue));
        }
        return asciiText;
    }

    QString hexText = QStringLiteral("0x");
    for (unsigned char byteValue : rowBytes) {
        hexText.append(core::formatByteValue(byteValue));
    }
    return hexText;
}

QString ByteTableModel::formatBits(const QByteArray& rowBits, const QString& displayFormat) const {
    if (rowBits.isEmpty()) {
        return {};
    }

    const QString normalizedFormat = normalizedDisplayFormat(displayFormat);
    if (normalizedFormat == QStringLiteral("binary")) {
        QString binaryText;
        binaryText.reserve(rowBits.size());
        for (char bitValue : rowBits) {
            binaryText.append(bitValue != 0 ? QLatin1Char('1') : QLatin1Char('0'));
        }
        return binaryText;
    }

    quint64 numericValue = 0;
    for (char bitValue : rowBits) {
        numericValue = (numericValue << 1) | (bitValue != 0 ? 1 : 0);
    }

    if (normalizedFormat == QStringLiteral("decimal")) {
        return QString::number(numericValue);
    }

    return core::formatBitsAsHexWithTrailingBits(rowBits);
}

int ByteTableModel::displayWidthBytes() const {
    if (dataSource_ == nullptr || frameLayout_ == nullptr) {
        return 0;
    }
    return frameLayout_->columnCount(*dataSource_);
}

std::optional<ByteTableModel::SingleByteSelection> ByteTableModel::singleByteSelection(
    const QSet<int>& visibleColumns
) const {
    if (visibleColumns.isEmpty()) {
        return std::nullopt;
    }

    QList<int> sortedColumns = visibleColumns.values();
    std::sort(sortedColumns.begin(), sortedColumns.end());

    SingleByteSelection selection;
    bool firstColumn = true;
    for (int visibleColumnIndex : sortedColumns) {
        if (visibleColumnIndex < 0 || visibleColumnIndex >= visibleColumns_.size()) {
            return std::nullopt;
        }

        const features::columns::VisibleByteColumn visibleColumn = visibleColumns_.at(visibleColumnIndex);
        if (visibleColumn.definitionIndex >= 0 || visibleColumn.isUndefined) {
            return std::nullopt;
        }

        if (firstColumn) {
            selection.byteIndex = visibleColumn.byteIndex;
            selection.startBit = visibleColumn.bitStart;
            selection.endBit = visibleColumn.bitEnd;
            firstColumn = false;
            continue;
        }

        if (visibleColumn.byteIndex != selection.byteIndex || visibleColumn.bitStart != selection.endBit + 1) {
            return std::nullopt;
        }
        selection.endBit = visibleColumn.bitEnd;
    }

    selection.bitWidth = selection.endBit - selection.startBit + 1;
    return selection;
}

QString ByteTableModel::splitGroupLabel(const QVector<SplitSegment>& splitSegments) const {
    for (const SplitSegment& splitSegment : splitSegments) {
        if (!splitSegment.label.trimmed().isEmpty() && !isAutoGeneratedLabel(splitSegment.label)) {
            return splitSegment.label.trimmed();
        }
    }
    return splitSegments.isEmpty() ? QString() : splitSegments.first().label.trimmed();
}

QString ByteTableModel::splitGroupColorName(const QVector<SplitSegment>& splitSegments) const {
    for (const SplitSegment& splitSegment : splitSegments) {
        if (!splitSegment.colorName.trimmed().isEmpty() && splitSegment.colorName != QStringLiteral("None")) {
            return splitSegment.colorName.trimmed();
        }
    }
    return QStringLiteral("None");
}

QVector<SplitSegment> ByteTableModel::currentSplitSegments(int byteIndex) const {
    return splitSegmentsForByte(byteIndex);
}

QVector<SplitSegment> ByteTableModel::replacementSegments(
    const QVector<SplitSegment>& sourceSegments,
    int targetStartBit,
    int targetEndBit,
    const QVector<SplitSegment>& replacementSegments
) const {
    QVector<SplitSegment> updatedSegments;
    bool replacedTarget = false;
    for (const SplitSegment& splitSegment : sourceSegments) {
        if (!replacedTarget
            && splitSegment.startBit == targetStartBit
            && splitSegment.endBit == targetEndBit) {
            updatedSegments += replacementSegments;
            replacedTarget = true;
            continue;
        }
        updatedSegments.append(splitSegment);
    }
    return replacedTarget ? updatedSegments : sourceSegments;
}

void ByteTableModel::applyCustomSplitSegments(
    int byteIndex,
    const SplitColumnState& splitState,
    const QVector<SplitSegment>& segments,
    int nextBinaryLabel,
    int nextNibbleLabel
) {
    SplitColumnState updatedState = splitState;
    updatedState.type = QStringLiteral("custom");
    updatedState.segments = segments;
    updatedState.nextBinaryLabel = nextBinaryLabel;
    updatedState.nextNibbleLabel = nextNibbleLabel;
    splitColumns_.insert(byteIndex, updatedState);
}

}  // namespace bitabyte::models
