#include "ui/inspection_controller.h"

#include "features/classification/frame_field_classification.h"
#include "features/inspector/field_inspector_analysis.h"
#include "models/byte_table_model.h"
#include "ui/byte_table_view.h"
#include "ui/field_current_value_panel.h"
#include "ui/field_inspector_panel.h"
#include "ui/frame_field_hints_panel.h"
#include "ui/live_bit_viewer_widget.h"
#include "ui/main_window_internal.h"

#include <QtConcurrent>

#include <QAbstractButton>
#include <QButtonGroup>
#include <QFutureWatcher>
#include <QLabel>
#include <QSpinBox>
#include <QTimer>

#include <algorithm>
#include <limits>

namespace bitabyte::ui {
namespace {

const QColor kCounterHighlightColor(212, 232, 255);
const QColor kConstantHighlightColor(255, 247, 196);

QString labelForVisibleColumnSnapshot(
    const features::columns::VisibleByteColumn& visibleColumn,
    const QVector<features::columns::ByteColumnDefinition>& columnDefinitions
) {
    if (visibleColumn.definitionIndex >= 0 && visibleColumn.definitionIndex < columnDefinitions.size()) {
        const QString explicitLabel = columnDefinitions.at(visibleColumn.definitionIndex).label.trimmed();
        if (!explicitLabel.isEmpty()) {
            return explicitLabel;
        }
    }

    const QString splitLabel = visibleColumn.splitLabel.trimmed();
    if (!splitLabel.isEmpty() && !detail::isAutoGeneratedLabel(splitLabel)) {
        return splitLabel;
    }

    return detail::defaultFieldLabel(visibleColumn, visibleColumn);
}

QString displayFormatForVisibleColumnSnapshot(
    const features::columns::VisibleByteColumn& visibleColumn,
    const QVector<features::columns::ByteColumnDefinition>& columnDefinitions
) {
    if (visibleColumn.definitionIndex >= 0 && visibleColumn.definitionIndex < columnDefinitions.size()) {
        const QString definitionDisplayFormat = columnDefinitions.at(visibleColumn.definitionIndex).displayFormat.trimmed();
        if (!definitionDisplayFormat.isEmpty()) {
            return definitionDisplayFormat;
        }
    }

    return visibleColumn.splitDisplayFormat.trimmed().isEmpty()
        ? QStringLiteral("hex")
        : visibleColumn.splitDisplayFormat;
}

QVector<LiveBitViewerWidget::PreviewBitHighlight> previewBitHighlightsForSelectedColumns(
    const QList<int>& selectedColumns,
    const models::ByteTableModel& byteTableModel,
    const QVector<features::classification::FrameFieldHint>& constantHints,
    const QVector<features::classification::FrameFieldHint>& counterHints
) {
    if (selectedColumns.isEmpty()) {
        return {};
    }

    int selectedStartBit = std::numeric_limits<int>::max();
    int selectedEndBit = std::numeric_limits<int>::min();
    for (int visibleColumnIndex : selectedColumns) {
        const features::columns::VisibleByteColumn visibleColumn = byteTableModel.visibleByteColumn(visibleColumnIndex);
        selectedStartBit = qMin(selectedStartBit, visibleColumn.absoluteStartBit);
        selectedEndBit = qMax(selectedEndBit, visibleColumn.absoluteEndBit);
    }
    if (selectedStartBit > selectedEndBit) {
        return {};
    }

    QVector<LiveBitViewerWidget::PreviewBitHighlight> bitHighlights;
    auto appendHighlights = [&](const QVector<features::classification::FrameFieldHint>& hints, const QColor& color) {
        for (const features::classification::FrameFieldHint& hint : hints) {
            const int highlightStartBit = qMax(selectedStartBit, hint.absoluteStartBit);
            const int highlightEndBit = qMin(selectedEndBit, hint.absoluteEndBit);
            if (highlightEndBit < highlightStartBit) {
                continue;
            }

            LiveBitViewerWidget::PreviewBitHighlight bitHighlight;
            bitHighlight.absoluteStartBit = highlightStartBit;
            bitHighlight.absoluteEndBit = highlightEndBit;
            bitHighlight.color = color;
            bitHighlights.append(bitHighlight);
        }
    };

    appendHighlights(constantHints, kConstantHighlightColor);
    appendHighlights(counterHints, kCounterHighlightColor);
    std::sort(
        bitHighlights.begin(),
        bitHighlights.end(),
        [](const LiveBitViewerWidget::PreviewBitHighlight& leftHighlight,
           const LiveBitViewerWidget::PreviewBitHighlight& rightHighlight) {
            if (leftHighlight.absoluteStartBit != rightHighlight.absoluteStartBit) {
                return leftHighlight.absoluteStartBit < rightHighlight.absoluteStartBit;
            }
            return leftHighlight.absoluteEndBit < rightHighlight.absoluteEndBit;
        }
    );
    return bitHighlights;
}

bool overlapsUserDefinition(
    const features::classification::FrameFieldHint& counterHint,
    const QVector<features::columns::ByteColumnDefinition>& columnDefinitions
) {
    for (const features::columns::ByteColumnDefinition& columnDefinition : columnDefinitions) {
        const int definitionStartBit = columnDefinition.startAbsoluteBit();
        const int definitionEndBit = columnDefinition.endAbsoluteBit();
        if (!(counterHint.absoluteEndBit < definitionStartBit || counterHint.absoluteStartBit > definitionEndBit)) {
            return true;
        }
    }
    return false;
}

QVector<features::columns::ByteColumnDefinition> detectedCounterDefinitions(
    const QVector<features::classification::FrameFieldHint>& counterHints,
    const QVector<features::columns::ByteColumnDefinition>& columnDefinitions
) {
    QVector<features::columns::ByteColumnDefinition> detectedDefinitions;
    int counterIndex = 1;
    for (const features::classification::FrameFieldHint& counterHint : counterHints) {
        if (counterHint.absoluteStartBit < 0 || counterHint.absoluteEndBit < counterHint.absoluteStartBit) {
            continue;
        }
        if (overlapsUserDefinition(counterHint, columnDefinitions)) {
            continue;
        }

        features::columns::ByteColumnDefinition detectedDefinition;
        detectedDefinition.label = QStringLiteral("Counter %1").arg(counterIndex++);
        detectedDefinition.displayFormat = QStringLiteral("decimal");
        detectedDefinition.colorName = QStringLiteral("Ocean");
        detectedDefinition.unit = QStringLiteral("bit");
        detectedDefinition.startBit = counterHint.absoluteStartBit;
        detectedDefinition.totalBits = counterHint.absoluteEndBit - counterHint.absoluteStartBit + 1;
        detectedDefinition.startByte = detectedDefinition.startBit / 8;
        detectedDefinition.endByte = detectedDefinition.endAbsoluteBit() / 8;
        detectedDefinitions.append(detectedDefinition);
    }
    return detectedDefinitions;
}

}  // namespace

InspectionController::InspectionController(
    data::ByteDataSource& dataSource,
    features::framing::FrameLayout& frameLayout,
    QVector<features::columns::ByteColumnDefinition>& columnDefinitions,
    models::ByteTableModel& byteTableModel,
    ByteTableView& byteTableView,
    LiveBitViewerWidget& liveBitViewerWidget,
    FrameFieldHintsPanel& frameFieldHintsPanel,
    FieldInspectorPanel& fieldInspectorPanel,
    FieldCurrentValuePanel& fieldCurrentValuePanel,
    QLabel& selectionInfoLabel,
    QButtonGroup& liveBitViewerModeGroup,
    QSpinBox& liveBitViewerSizeSpinBox,
    SelectionCallbacks selectionCallbacks,
    QObject* parent
)
    : QObject(parent),
      dataSource_(dataSource),
      frameLayout_(frameLayout),
      columnDefinitions_(columnDefinitions),
      byteTableModel_(byteTableModel),
      byteTableView_(byteTableView),
      liveBitViewerWidget_(liveBitViewerWidget),
      frameFieldHintsPanel_(frameFieldHintsPanel),
      fieldInspectorPanel_(fieldInspectorPanel),
      fieldCurrentValuePanel_(fieldCurrentValuePanel),
      selectionInfoLabel_(selectionInfoLabel),
      liveBitViewerModeGroup_(liveBitViewerModeGroup),
      liveBitViewerSizeSpinBox_(liveBitViewerSizeSpinBox),
      selectionCallbacks_(std::move(selectionCallbacks)),
      liveBitViewerRefreshTimer_(new QTimer(this)),
      fieldInspectorRefreshTimer_(new QTimer(this)),
      frameFieldHintsRefreshTimer_(new QTimer(this)),
      fieldInspectorWatcher_(new QFutureWatcher<features::inspector::FieldInspectorAnalysis>(this)),
      frameFieldHintsWatcher_(new QFutureWatcher<features::classification::FrameFieldClassificationResult>(this)) {
    liveBitViewerRefreshTimer_->setSingleShot(true);
    liveBitViewerRefreshTimer_->setInterval(0);
    connect(liveBitViewerRefreshTimer_, &QTimer::timeout, this, [this]() { refreshLiveBitViewer(); });

    fieldInspectorRefreshTimer_->setSingleShot(true);
    fieldInspectorRefreshTimer_->setInterval(0);
    connect(fieldInspectorRefreshTimer_, &QTimer::timeout, this, [this]() { refreshFieldInspector(); });

    frameFieldHintsRefreshTimer_->setSingleShot(true);
    frameFieldHintsRefreshTimer_->setInterval(0);
    connect(frameFieldHintsRefreshTimer_, &QTimer::timeout, this, [this]() { refreshFrameFieldHints(); });

    connect(
        fieldInspectorWatcher_,
        &QFutureWatcher<features::inspector::FieldInspectorAnalysis>::finished,
        this,
        [this]() {
            if (activeFieldInspectorRequestId_ == fieldInspectorRequestId_) {
                const features::inspector::FieldInspectorAnalysis result = fieldInspectorWatcher_->result();
                if (frameLayout_.isFramed()) {
                    fieldInspectorPanel_.setAnalysis(result);
                } else {
                    fieldInspectorPanel_.showUnavailable();
                }
                fieldCurrentValuePanel_.setAnalysis(result);
                return;
            }

            refreshFieldInspector();
        }
    );

    connect(
        frameFieldHintsWatcher_,
        &QFutureWatcher<features::classification::FrameFieldClassificationResult>::finished,
        this,
        [this]() {
            if (activeFrameFieldHintsRequestId_ == frameFieldHintsRequestId_) {
                const features::classification::FrameFieldClassificationResult classificationResult =
                    frameFieldHintsWatcher_->result();
                classifiedCounterHints_ = classificationResult.counterHints;
                classifiedConstantHints_ = classificationResult.constantHints;
                classifiedCounterVisibleColumnIndices_ = classificationResult.counterVisibleColumnIndices;
                classifiedConstantVisibleColumnIndices_ = classificationResult.constantVisibleColumnIndices;
                frameFieldHintsPanel_.setHints(classificationResult);
                byteTableModel_.setDetectedFieldDefinitions(
                    detectedCounterDefinitions(classificationResult.counterHints, columnDefinitions_)
                );
                byteTableModel_.setCounterHighlightedVisibleColumns({});
                refreshLiveBitViewer();
                return;
            }

            refreshFrameFieldHints();
        }
    );
}

void InspectionController::scheduleLiveBitViewerRefresh() {
    if (!liveBitViewerRefreshTimer_->isActive()) {
        liveBitViewerRefreshTimer_->start();
    }
}

void InspectionController::refreshLiveBitViewer() {
    liveBitViewerWidget_.setDisplayMode(currentLiveBitViewerMode());
    liveBitViewerWidget_.setCellSize(liveBitViewerSizeSpinBox_.value());

    const QSet<int> selectedColumnSet = selectionCallbacks_.selectedVisibleColumns != nullptr
        ? selectionCallbacks_.selectedVisibleColumns()
        : QSet<int>{};
    if (!dataSource_.hasData() || !frameLayout_.isFramed() || selectedColumnSet.isEmpty()) {
        liveBitViewerWidget_.setPreviewSource(nullptr, nullptr, {}, 0, 0);
        liveBitViewerWidget_.setPreviewColumnHighlights({});
        liveBitViewerWidget_.setPreviewBitHighlights({});
        return;
    }

    QList<int> selectedColumns = selectedColumnSet.values();
    std::sort(selectedColumns.begin(), selectedColumns.end());

    constexpr int kMaxLivePreviewRows = 128;
    const int frameRowCount = static_cast<int>(frameLayout_.rowCount(dataSource_));
    const QModelIndex anchorIndex = selectionCallbacks_.topSelectedDataIndex != nullptr
        ? selectionCallbacks_.topSelectedDataIndex()
        : QModelIndex{};
    const int anchorRow = anchorIndex.isValid() ? anchorIndex.row() : 0;
    const int previewRowCount = qMin(frameRowCount, kMaxLivePreviewRows);
    const int firstPreviewRow = frameRowCount <= previewRowCount
        ? 0
        : qBound(0, anchorRow - (previewRowCount / 2), frameRowCount - previewRowCount);

    QVector<features::columns::VisibleByteColumn> previewColumns;
    previewColumns.reserve(selectedColumns.size());
    for (int visibleColumnIndex : selectedColumns) {
        previewColumns.append(byteTableModel_.visibleByteColumn(visibleColumnIndex));
    }

    liveBitViewerWidget_.setPreviewSource(
        &dataSource_,
        &frameLayout_,
        previewColumns,
        firstPreviewRow,
        previewRowCount
    );
    liveBitViewerWidget_.setPreviewColumnHighlights({});
    liveBitViewerWidget_.setPreviewBitHighlights(
        previewBitHighlightsForSelectedColumns(
            selectedColumns,
            byteTableModel_,
            classifiedConstantHints_,
            classifiedCounterHints_
        )
    );
}

void InspectionController::refreshFieldInspector() {
    if (!dataSource_.hasData()) {
        ++fieldInspectorRequestId_;
        fieldInspectorPanel_.clearAnalysis();
        fieldCurrentValuePanel_.clearAnalysis();
        return;
    }

    if (!frameLayout_.isFramed()) {
        fieldInspectorPanel_.showUnavailable();
    }

    QSet<int> inspectedColumns = selectionCallbacks_.selectedVisibleColumns != nullptr
        ? selectionCallbacks_.selectedVisibleColumns()
        : QSet<int>{};
    if (inspectedColumns.size() == 1 && selectionCallbacks_.editableVisibleColumnsForSeed != nullptr) {
        inspectedColumns = selectionCallbacks_.editableVisibleColumnsForSeed(*inspectedColumns.begin());
    }

    QModelIndex anchorIndex = byteTableView_.currentIndex();
    int anchorVisibleColumnIndex = byteTableModel_.visibleColumnIndexForModelIndex(anchorIndex);
    if (inspectedColumns.isEmpty() && anchorVisibleColumnIndex >= 0
        && selectionCallbacks_.editableVisibleColumnsForSeed != nullptr) {
        inspectedColumns = selectionCallbacks_.editableVisibleColumnsForSeed(anchorVisibleColumnIndex);
    }

    if (inspectedColumns.isEmpty() || !byteTableModel_.visibleColumnsAreContiguous(inspectedColumns)) {
        ++fieldInspectorRequestId_;
        fieldInspectorPanel_.clearAnalysis();
        fieldCurrentValuePanel_.clearAnalysis();
        return;
    }

    QList<int> sortedVisibleColumns = inspectedColumns.values();
    std::sort(sortedVisibleColumns.begin(), sortedVisibleColumns.end());

    const features::columns::VisibleByteColumn firstVisibleColumn =
        byteTableModel_.visibleByteColumn(sortedVisibleColumns.first());
    const features::columns::VisibleByteColumn lastVisibleColumn =
        byteTableModel_.visibleByteColumn(sortedVisibleColumns.last());

    QString fieldLabel = detail::defaultFieldLabel(firstVisibleColumn, lastVisibleColumn);
    const int definitionIndex = selectionCallbacks_.definitionIndexForVisibleColumns != nullptr
        ? selectionCallbacks_.definitionIndexForVisibleColumns(inspectedColumns)
        : -1;
    if (definitionIndex >= 0 && definitionIndex < columnDefinitions_.size()) {
        const QString explicitLabel = columnDefinitions_.at(definitionIndex).label.trimmed();
        if (!explicitLabel.isEmpty()) {
            fieldLabel = explicitLabel;
        }
    } else {
        QString sharedSplitLabel;
        bool allVisibleColumnsShareSplit = true;
        for (int visibleColumnIndex : sortedVisibleColumns) {
            const features::columns::VisibleByteColumn visibleColumn =
                byteTableModel_.visibleByteColumn(visibleColumnIndex);
            const QString splitLabel = visibleColumn.splitLabel.trimmed();
            if (splitLabel.isEmpty()) {
                allVisibleColumnsShareSplit = false;
                break;
            }

            if (sharedSplitLabel.isEmpty()) {
                sharedSplitLabel = splitLabel;
                continue;
            }

            if (sharedSplitLabel != splitLabel) {
                allVisibleColumnsShareSplit = false;
                break;
            }
        }

        if (allVisibleColumnsShareSplit && !sharedSplitLabel.isEmpty()) {
            fieldLabel = sharedSplitLabel;
        }
    }

    if (anchorVisibleColumnIndex < 0 || byteTableModel_.isFrameLengthColumn(anchorIndex.column())) {
        anchorIndex = selectionCallbacks_.topSelectedDataIndex != nullptr
            ? selectionCallbacks_.topSelectedDataIndex()
            : QModelIndex{};
        anchorVisibleColumnIndex = byteTableModel_.visibleColumnIndexForModelIndex(anchorIndex);
    }

    const int anchorRow = anchorIndex.isValid() ? anchorIndex.row() : -1;
    features::inspector::FieldSelection fieldSelection;
    fieldSelection.label = fieldLabel;
    fieldSelection.startBit = firstVisibleColumn.absoluteStartBit;
    fieldSelection.endBit = lastVisibleColumn.absoluteEndBit;
    const int startByteIndex = fieldSelection.startBit / 8;
    const int endByteIndex = fieldSelection.endBit / 8;
    const QString byteRangeText = startByteIndex == endByteIndex
        ? QStringLiteral("byte %1").arg(startByteIndex)
        : QStringLiteral("bytes %1-%2").arg(startByteIndex).arg(endByteIndex);
    const QString positionText = QStringLiteral("bits %1-%2 | %3")
        .arg(fieldSelection.startBit)
        .arg(fieldSelection.endBit)
        .arg(byteRangeText);
    if (frameLayout_.isFramed()) {
        fieldInspectorPanel_.setPendingAnalysis(fieldLabel, positionText);
    } else {
        fieldInspectorPanel_.showUnavailable();
    }
    fieldCurrentValuePanel_.setPendingAnalysis(fieldLabel, positionText);
    ++fieldInspectorRequestId_;
    if (fieldInspectorWatcher_->isRunning()) {
        return;
    }

    startFieldInspectorAnalysis(fieldSelection, anchorRow, fieldInspectorRequestId_);
}

void InspectionController::scheduleFrameFieldHintsRefresh() {
    if (!frameFieldHintsRefreshTimer_->isActive()) {
        frameFieldHintsRefreshTimer_->start();
    }
}

void InspectionController::refreshFrameFieldHints() {
    if (!dataSource_.hasData() || !frameLayout_.isFramed()) {
        ++frameFieldHintsRequestId_;
        frameFieldHintsPanel_.showUnavailable();
        classifiedCounterHints_.clear();
        classifiedConstantHints_.clear();
        classifiedCounterVisibleColumnIndices_.clear();
        classifiedConstantVisibleColumnIndices_.clear();
        byteTableModel_.setDetectedFieldDefinitions({});
        byteTableModel_.setCounterHighlightedVisibleColumns({});
        liveBitViewerWidget_.setPreviewColumnHighlights({});
        liveBitViewerWidget_.setPreviewBitHighlights({});
        return;
    }

    QVector<features::classification::FrameFieldColumnSnapshot> columnSnapshots;
    columnSnapshots.reserve(byteTableModel_.visibleColumnCount());
    for (int visibleColumnIndex = 0; visibleColumnIndex < byteTableModel_.visibleColumnCount(); ++visibleColumnIndex) {
        const features::columns::VisibleByteColumn visibleColumn = byteTableModel_.visibleByteColumn(visibleColumnIndex);
        features::classification::FrameFieldColumnSnapshot columnSnapshot;
        columnSnapshot.visibleColumnIndex = visibleColumnIndex;
        columnSnapshot.visibleColumn = visibleColumn;
        columnSnapshot.label = labelForVisibleColumnSnapshot(visibleColumn, columnDefinitions_);
        columnSnapshot.displayFormat = displayFormatForVisibleColumnSnapshot(visibleColumn, columnDefinitions_);
        columnSnapshots.append(columnSnapshot);
    }

    if (columnSnapshots.isEmpty()) {
        ++frameFieldHintsRequestId_;
        frameFieldHintsPanel_.setHints({});
        classifiedCounterHints_.clear();
        classifiedConstantHints_.clear();
        classifiedCounterVisibleColumnIndices_.clear();
        classifiedConstantVisibleColumnIndices_.clear();
        byteTableModel_.setDetectedFieldDefinitions({});
        byteTableModel_.setCounterHighlightedVisibleColumns({});
        liveBitViewerWidget_.setPreviewColumnHighlights({});
        liveBitViewerWidget_.setPreviewBitHighlights({});
        return;
    }

    frameFieldHintsPanel_.setPendingAnalysis();
    ++frameFieldHintsRequestId_;
    if (frameFieldHintsWatcher_->isRunning()) {
        return;
    }

    activeFrameFieldHintsRequestId_ = frameFieldHintsRequestId_;
    const data::ByteDataSource dataSourceSnapshot = dataSource_;
    const features::framing::FrameLayout frameLayoutSnapshot = frameLayout_;
    const QVector<features::classification::FrameFieldColumnSnapshot> columnSnapshotsSnapshot = columnSnapshots;
    frameFieldHintsWatcher_->setFuture(QtConcurrent::run(
        [dataSourceSnapshot, frameLayoutSnapshot, columnSnapshotsSnapshot]() {
            features::classification::FrameFieldClassificationResult result =
                features::classification::classifyFramedVisibleColumns(
                    dataSourceSnapshot,
                    frameLayoutSnapshot,
                    columnSnapshotsSnapshot
                );

            // Gradient-based scan for non-byte-aligned and arbitrary-width counters.
            // Run separately here (not inside classifyFramedVisibleColumns) so it doesn't
            // interfere with the sync discovery dialog's own gradient scan call.
            const qsizetype frameLengthBits = frameLayoutSnapshot.rowLengthBits(dataSourceSnapshot, 0);
            if (frameLengthBits > 2) {
                const QVector<features::classification::FrameFieldHint> gradientHints =
                    features::classification::discoverCounterHintsByBitWindow(
                        dataSourceSnapshot,
                        frameLayoutSnapshot,
                        columnSnapshotsSnapshot,
                        0,
                        static_cast<int>(frameLengthBits) - 1
                    );
                for (const features::classification::FrameFieldHint& hint : gradientHints) {
                    if (hint.visibleColumnIndices.isEmpty()) {
                        continue;
                    }
                    bool overlaps = false;
                    for (const features::classification::FrameFieldHint& existing : result.counterHints) {
                        if (!(hint.absoluteEndBit < existing.absoluteStartBit
                              || hint.absoluteStartBit > existing.absoluteEndBit)) {
                            overlaps = true;
                            break;
                        }
                    }
                    if (!overlaps) {
                        result.counterHints.append(hint);
                        for (int visibleColumnIndex : hint.visibleColumnIndices) {
                            result.counterVisibleColumnIndices.insert(visibleColumnIndex);
                        }
                    }
                }
            }

            return result;
        }
    ));
}

void InspectionController::updateSelectionStatus() {
    const QModelIndex currentIndex = byteTableView_.currentIndex();
    if (frameLayout_.isFramed() && byteTableModel_.isFrameLengthColumn(currentIndex.column())) {
        selectionInfoLabel_.setText(
            QStringLiteral("Selection: frame row %1 | length %2 bytes | %3 bits")
                .arg(currentIndex.row())
                .arg(frameLayout_.rowLengthBytes(dataSource_, currentIndex.row()))
                .arg(frameLayout_.rowLengthBits(dataSource_, currentIndex.row()))
        );
        scheduleFieldInspectorRefresh();
        return;
    }

    const qsizetype startBit = byteTableModel_.displayStartBitForIndex(currentIndex);
    if (!dataSource_.isBitOffsetValid(startBit)) {
        selectionInfoLabel_.setText(QStringLiteral("Selection: none"));
        scheduleFieldInspectorRefresh();
        return;
    }

    const QString rowLabel = frameLayout_.isFramed() ? QStringLiteral("frame row") : QStringLiteral("row");
    const int visibleColumnIndex = byteTableModel_.visibleColumnIndexForModelIndex(currentIndex);
    const features::columns::VisibleByteColumn visibleColumn = byteTableModel_.visibleByteColumn(visibleColumnIndex);
    const QString valueText = currentIndex.data(Qt::DisplayRole).toString();
    selectionInfoLabel_.setText(
        QStringLiteral("Selection: start bit %1 | %2 %3 col %4 | bits %5-%6 | value %7")
            .arg(startBit)
            .arg(rowLabel)
            .arg(currentIndex.row())
            .arg(visibleColumnIndex >= 0 ? visibleColumnIndex : currentIndex.column())
            .arg(visibleColumn.absoluteStartBit)
            .arg(visibleColumn.absoluteEndBit)
            .arg(valueText)
    );
    scheduleFieldInspectorRefresh();
}

void InspectionController::scheduleFieldInspectorRefresh() {
    if (!fieldInspectorRefreshTimer_->isActive()) {
        fieldInspectorRefreshTimer_->start();
    }
}

void InspectionController::startFieldInspectorAnalysis(
    const features::inspector::FieldSelection& fieldSelection,
    int currentRow,
    quint64 requestId
) {
    activeFieldInspectorRequestId_ = requestId;
    const data::ByteDataSource dataSourceSnapshot = dataSource_;
    const features::framing::FrameLayout frameLayoutSnapshot = frameLayout_;
    const features::inspector::FieldSelection fieldSelectionSnapshot = fieldSelection;
    fieldInspectorWatcher_->setFuture(QtConcurrent::run(
        [dataSourceSnapshot, frameLayoutSnapshot, fieldSelectionSnapshot, currentRow]() {
            return features::inspector::analyzeField(
                dataSourceSnapshot,
                frameLayoutSnapshot,
                fieldSelectionSnapshot,
                currentRow,
                frameLayoutSnapshot.isFramed()
            );
        }
    ));
}

QString InspectionController::currentLiveBitViewerMode() const {
    if (liveBitViewerModeGroup_.checkedButton() == nullptr) {
        return QStringLiteral("squares");
    }

    return liveBitViewerModeGroup_.checkedButton()->text().trimmed().toLower();
}

}  // namespace bitabyte::ui
