#pragma once

#include <QString>

#include "features/columns/visible_byte_column.h"

namespace bitabyte::ui::detail {

inline bool isAutoGeneratedLabel(const QString& labelText) {
    const QString trimmedLabel = labelText.trimmed();
    return trimmedLabel.isEmpty()
        || trimmedLabel.startsWith(QStringLiteral("BIN "))
        || trimmedLabel.startsWith(QStringLiteral("NIBBLE "))
        || trimmedLabel.startsWith(QStringLiteral("Byte "))
        || trimmedLabel.startsWith(QStringLiteral("Bytes "))
        || trimmedLabel.startsWith(QStringLiteral("Combo "));
}

inline QString defaultFieldLabel(const features::columns::VisibleByteColumn& firstVisibleColumn,
                                 const features::columns::VisibleByteColumn& lastVisibleColumn) {
    const bool startsOnByteBoundary = firstVisibleColumn.absoluteStartBit % 8 == 0;
    const bool endsOnByteBoundary = lastVisibleColumn.absoluteEndBit % 8 == 7;
    const int startByteIndex = firstVisibleColumn.absoluteStartBit / 8;
    const int endByteIndex = lastVisibleColumn.absoluteEndBit / 8;

    if (startsOnByteBoundary && endsOnByteBoundary) {
        if (startByteIndex == endByteIndex) {
            return QStringLiteral("Byte %1").arg(startByteIndex);
        }
        return QStringLiteral("Bytes %1-%2").arg(startByteIndex).arg(endByteIndex);
    }

    return QStringLiteral("Bits %1-%2")
        .arg(firstVisibleColumn.absoluteStartBit)
        .arg(lastVisibleColumn.absoluteEndBit);
}

inline constexpr int kPreferredMainWindowWidth = 1720;
inline constexpr int kPreferredMainWindowHeight = 920;
inline constexpr int kMinimumComfortableMainWindowWidth = 1500;
inline constexpr int kMinimumComfortableMainWindowHeight = 860;
inline constexpr int kInitialColumnDefinitionsDockWidth = 320;
inline constexpr int kInitialLiveBitViewerDockWidth = 480;
inline constexpr int kMinimumLiveBitViewerDockWidth = 460;

inline QString rowOrderButtonLabel(const QString& labelText, bool descending) {
    return QStringLiteral("%1 %2")
        .arg(labelText)
        .arg(descending ? QStringLiteral("\u2193") : QStringLiteral("\u2191"));
}

}  // namespace bitabyte::ui::detail
