#pragma once

#include <QHash>
#include <QString>
#include <QStringList>
#include <QVector>

#include <limits>

#include "features/columns/byte_column_definition.h"
#include "features/columns/visible_byte_column.h"

namespace bitabyte::ui::detail {

inline bool isAutoGeneratedLabel(const QString& labelText) {
    const QString trimmedLabel = labelText.trimmed();
    return trimmedLabel.isEmpty()
        || trimmedLabel.startsWith(QStringLiteral("BIN "))
        || trimmedLabel.startsWith(QStringLiteral("NIBBLE "))
        || trimmedLabel.startsWith(QStringLiteral("Byte "))
        || trimmedLabel.startsWith(QStringLiteral("Bytes "))
        || trimmedLabel.startsWith(QStringLiteral("Combo "));
}

inline QString defaultFieldLabel(const features::columns::VisibleByteColumn& firstVisibleColumn,
                                 const features::columns::VisibleByteColumn& lastVisibleColumn) {
    const bool startsOnByteBoundary = firstVisibleColumn.absoluteStartBit % 8 == 0;
    const bool endsOnByteBoundary = lastVisibleColumn.absoluteEndBit % 8 == 7;
    const int startByteIndex = firstVisibleColumn.absoluteStartBit / 8;
    const int endByteIndex = lastVisibleColumn.absoluteEndBit / 8;

    if (startsOnByteBoundary && endsOnByteBoundary) {
        if (startByteIndex == endByteIndex) {
            return QStringLiteral("Byte %1").arg(startByteIndex);
        }
        return QStringLiteral("Bytes %1-%2").arg(startByteIndex).arg(endByteIndex);
    }

    return QStringLiteral("Bits %1-%2")
        .arg(firstVisibleColumn.absoluteStartBit)
        .arg(lastVisibleColumn.absoluteEndBit);
}

inline QString nextAutoColumnColorName(
    const QVector<features::columns::ByteColumnDefinition>& columnDefinitions
) {
    static const QStringList autoColorSequence = {
        QStringLiteral("Sky"),
        QStringLiteral("Coral"),
        QStringLiteral("Mint"),
        QStringLiteral("Gold"),
        QStringLiteral("Lilac"),
        QStringLiteral("Sunshine"),
    };

    QHash<QString, int> usedCounts;
    for (const QString& colorName : autoColorSequence) {
        usedCounts.insert(colorName, 0);
    }

    for (const features::columns::ByteColumnDefinition& definition : columnDefinitions) {
        if (usedCounts.contains(definition.colorName)) {
            usedCounts[definition.colorName] += 1;
        }
    }

    QString bestColor = autoColorSequence.first();
    int bestCount = std::numeric_limits<int>::max();
    for (const QString& colorName : autoColorSequence) {
        const int usedCount = usedCounts.value(colorName, 0);
        if (usedCount < bestCount) {
            bestCount = usedCount;
            bestColor = colorName;
        }
    }

    return bestColor;
}

inline constexpr int kPreferredMainWindowWidth = 1720;
inline constexpr int kPreferredMainWindowHeight = 920;
inline constexpr int kMinimumComfortableMainWindowWidth = 1500;
inline constexpr int kMinimumComfortableMainWindowHeight = 860;
inline constexpr int kInitialColumnDefinitionsDockWidth = 320;
inline constexpr int kInitialLiveBitViewerDockWidth = 480;
inline constexpr int kMinimumLiveBitViewerDockWidth = 460;

inline QString rowOrderButtonLabel(const QString& labelText, bool descending) {
    return QStringLiteral("%1 %2")
        .arg(labelText)
        .arg(descending ? QStringLiteral("\u2193") : QStringLiteral("\u2191"));
}

}  // namespace bitabyte::ui::detail
